/* Generated By:JJTree: Do not edit this line. SLActionExpression.java */

package org.jamocha.languages.sl.parser;

public class SLActionExpression extends SimpleNode {
  public SLActionExpression(int id) {
    super(id);
  }

  public SLActionExpression(SLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
