/* Generated By:JJTree: Do not edit this line. SLAgent.java */

package org.jamocha.languages.sl.parser;

public class SLAgent extends SimpleNode {
  public SLAgent(int id) {
    super(id);
  }

  public SLAgent(SLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
