/* Generated By:JJTree: Do not edit this line. SLBooleanSymbol.java */

package org.jamocha.languages.sl.parser;

public class SLBooleanSymbol extends SimpleNode {
  public SLBooleanSymbol(int id) {
    super(id);
  }

  public SLBooleanSymbol(SLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
