/* Generated By:JJTree: Do not edit this line. SLReferentialOp.java */

package org.jamocha.languages.sl.parser;

public class SLReferentialOp extends SimpleNode {
  public SLReferentialOp(int id) {
    super(id);
  }

  public SLReferentialOp(SLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
