/* Generated By:JJTree: Do not edit this line. SFPAutoFocus.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=SFP,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jamocha.languages.clips.parser;

public class SFPAutoFocus extends SimpleNode {
	public SFPAutoFocus(int id) {
		super(id);
	}

	public SFPAutoFocus(SFPParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(SFPParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
/*
 * JavaCC - OriginalChecksum=09216cd8cfe57c8f40e17795395c6162 (do not edit this
 * line)
 */
