/* Generated By:JJTree: Do not edit this line. SFPAttributes.java */

package org.jamocha.languages.clips.parser;

public class SFPAttributes extends SimpleNode {
  public SFPAttributes(int id) {
    super(id);
  }

  public SFPAttributes(SFPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SFPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
