/* Generated By:JJTree: Do not edit this line. SFPConstructDescription.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=SFP,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jamocha.languages.clips.parser;

public class SFPConstructDescription extends SimpleNode {
	public SFPConstructDescription(int id) {
		super(id);
	}

	public SFPConstructDescription(SFPParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(SFPParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
/*
 * JavaCC - OriginalChecksum=83a909718f36aae3165bbefa7077c486 (do not edit this
 * line)
 */
