/* Generated By:JJTree: Do not edit this line. SFPConnectedConstraint.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=SFP,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jamocha.languages.clips.parser;

public class SFPConnectedConstraint extends SimpleNode {
	public SFPConnectedConstraint(int id) {
		super(id);
	}

	public SFPConnectedConstraint(SFPParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(SFPParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
/*
 * JavaCC - OriginalChecksum=3329f7662d67a09209bd45b854187e6c (do not edit this
 * line)
 */
