/* Generated By:JJTree: Do not edit this line. SFPColon.java */

package org.jamocha.languages.clips.parser;

public class SFPColon extends SimpleNode {
  public SFPColon(int id) {
    super(id);
  }

  public SFPColon(SFPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SFPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
