/* Generated By:JJTree: Do not edit this line. SFPDateTimeType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=SFP,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jamocha.languages.clips.parser;

public class SFPDateTimeType extends SimpleNode {
	public SFPDateTimeType(int id) {
		super(id);
	}

	public SFPDateTimeType(SFPParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(SFPParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
/*
 * JavaCC - OriginalChecksum=c1ef4cac48b351a70786b3ca5aab8b4b (do not edit this
 * line)
 */
