/* Generated By:JJTree: Do not edit this line. SFPDefgenericConstruct.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=SFP,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jamocha.languages.clips.parser;

public class SFPDefgenericConstruct extends SimpleNode {
	public SFPDefgenericConstruct(int id) {
		super(id);
	}

	public SFPDefgenericConstruct(SFPParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(SFPParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
/*
 * JavaCC - OriginalChecksum=9a096a3f19fd27ab9024143d6960d059 (do not edit this
 * line)
 */
