/* Generated By:JJTree: Do not edit this line. SFPForallCE.java */

package org.jamocha.languages.clips.parser;

public class SFPForallCE extends SimpleNode {
  public SFPForallCE(int id) {
    super(id);
  }

  public SFPForallCE(SFPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SFPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
