/* Generated By:JJTree: Do not edit this line. SFPFunctionGroup.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=SFP,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jamocha.languages.clips.parser;

public class SFPFunctionGroup extends SimpleNode {
	public SFPFunctionGroup(int id) {
		super(id);
	}

	public SFPFunctionGroup(SFPParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(SFPParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
/*
 * JavaCC - OriginalChecksum=1847c748e55e830c1b05e3f10b701776 (do not edit this
 * line)
 */
