/* Generated By:JJTree: Do not edit this line. SFPGlobalVariable.java */

package org.jamocha.languages.clips.parser;

public class SFPGlobalVariable extends SimpleNode {
  public SFPGlobalVariable(int id) {
    super(id);
  }

  public SFPGlobalVariable(SFPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SFPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
