/* Generated By:JJTree: Do not edit this line. SFPIntegerType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=SFP,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jamocha.languages.clips.parser;

public class SFPIntegerType extends SimpleNode {
	public SFPIntegerType(int id) {
		super(id);
	}

	public SFPIntegerType(SFPParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(SFPParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
/*
 * JavaCC - OriginalChecksum=1fc801053d5c59ba7bbab480f4ced647 (do not edit this
 * line)
 */
