/* Generated By:JJTree: Do not edit this line. SFPIntegerList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=SFP,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jamocha.languages.clips.parser;

public class SFPIntegerList extends SimpleNode {
	public SFPIntegerList(int id) {
		super(id);
	}

	public SFPIntegerList(SFPParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(SFPParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
/*
 * JavaCC - OriginalChecksum=392cdd3df5f4af695b1d0f6a5e382959 (do not edit this
 * line)
 */
