/* Generated By:JJTree: Do not edit this line. SFPIntegerType.java */

package org.jamocha.languages.clips.parser;

public class SFPIntegerType extends SimpleNode {
  public SFPIntegerType(int id) {
    super(id);
  }

  public SFPIntegerType(SFPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SFPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
