/* Generated By:JJTree: Do not edit this line. SFPLexemeList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=SFP,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jamocha.languages.clips.parser;

public class SFPLexemeList extends SimpleNode {
	public SFPLexemeList(int id) {
		super(id);
	}

	public SFPLexemeList(SFPParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(SFPParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
/*
 * JavaCC - OriginalChecksum=e717193d64d332fb1bf0230086b9f574 (do not edit this
 * line)
 */
