/* Generated By:JJTree: Do not edit this line. SFPModifyPattern.java */

package org.jamocha.languages.clips.parser;

public class SFPModifyPattern extends SimpleNode {
  public SFPModifyPattern(int id) {
    super(id);
  }

  public SFPModifyPattern(SFPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SFPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
