/* Generated By:JJTree: Do not edit this line. SFPModifyPattern.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=SFP,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jamocha.languages.clips.parser;

public class SFPModifyPattern extends SimpleNode {
	public SFPModifyPattern(int id) {
		super(id);
	}

	public SFPModifyPattern(SFPParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(SFPParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
/*
 * JavaCC - OriginalChecksum=1039e9fa9ff850362802bcdc77e981cc (do not edit this
 * line)
 */
