/* Generated By:JJTree: Do not edit this line. SFPMultiVariable.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=SFP,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jamocha.languages.clips.parser;

public class SFPMultiVariable extends SimpleNode {
	public SFPMultiVariable(int id) {
		super(id);
	}

	public SFPMultiVariable(SFPParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(SFPParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
/*
 * JavaCC - OriginalChecksum=3f6526ed6b45881445ef7dee6134b232 (do not edit this
 * line)
 */
