/* Generated By:JJTree: Do not edit this line. SFPParameterRestriction.java */

package org.jamocha.languages.clips.parser;

public class SFPParameterRestriction extends SimpleNode {
  public SFPParameterRestriction(int id) {
    super(id);
  }

  public SFPParameterRestriction(SFPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SFPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
