/* Generated By:JJTree: Do not edit this line. /home/free-radical/Workspace/Jamocha/src/org/jamocha/languages/clips/parser/SFPParserTreeConstants.java */

package org.jamocha.languages.clips.parser;

public interface SFPParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTFLOAT = 1;
  public int JJTINTEGER = 2;
  public int JJTDATETIME = 3;
  public int JJTVOID = 4;
  public int JJTSYMBOL = 5;
  public int JJTSTRING = 6;
  public int JJTTRUE = 7;
  public int JJTNIL = 8;
  public int JJTSYMBOLTYPE = 9;
  public int JJTSTRINGTYPE = 10;
  public int JJTDATETIMETYPE = 11;
  public int JJTLEXEMETYPE = 12;
  public int JJTBOOLEANTYPE = 13;
  public int JJTINTEGERTYPE = 14;
  public int JJTLONGTYPE = 15;
  public int JJTSHORTTYPE = 16;
  public int JJTFLOATTYPE = 17;
  public int JJTDOUBLETYPE = 18;
  public int JJTNUMBERTYPE = 19;
  public int JJTFALSE = 20;
  public int JJTCONSTANT = 21;
  public int JJTCONSTRUCTDESCRIPTION = 22;
  public int JJTSINGLEVARIABLE = 23;
  public int JJTGLOBALVARIABLE = 24;
  public int JJTMULTIVARIABLE = 25;
  public int JJTVARIABLETYPE = 26;
  public int JJTANYFUNCTION = 27;
  public int JJTEXPRESSION = 28;
  public int JJTASSERTFUNC = 29;
  public int JJTMODIFY = 30;
  public int JJTFINDFACTBYFACTFUNC = 31;
  public int JJTRETRACTFUNC = 32;
  public int JJTIFELSEFUNC = 33;
  public int JJTWHILEFUNC = 34;
  public int JJTLOOPFORCOUNTFUNC = 35;
  public int JJTSWITCHCASEFUNC = 36;
  public int JJTCASESTATEMENT = 37;
  public int JJTSWITCHDEFAULTS = 38;
  public int JJTDEFTEMPLATECONSTRUCT = 39;
  public int JJTSILENT = 40;
  public int JJTSLOTDEFINITION = 41;
  public int JJTSINGLESLOTDEFINITION = 42;
  public int JJTMULTISLOTDEFINITION = 43;
  public int JJTATTRIBUTES = 44;
  public int JJTDEFAULTATTRIBUTE = 45;
  public int JJTDEFAULTATTRIBUTES = 46;
  public int JJTDERIVEATTRIBUTE = 47;
  public int JJTNONEATTRIBUTE = 48;
  public int JJTDYNAMICATTRIBUTE = 49;
  public int JJTMODIFYPATTERN = 50;
  public int JJTRHSSLOT = 51;
  public int JJTRHSPATTERN = 52;
  public int JJTDEFRULECONSTRUCT = 53;
  public int JJTACTIONLIST = 54;
  public int JJTDECLARATION = 55;
  public int JJTTEMPORALVALIDITYDECLARATION = 56;
  public int JJTTEMPORALVALIDITY = 57;
  public int JJTTAMILLISECOND = 58;
  public int JJTTASECOND = 59;
  public int JJTTAMINUTE = 60;
  public int JJTTAHOUR = 61;
  public int JJTTADAY = 62;
  public int JJTTAMONTH = 63;
  public int JJTTAYEAR = 64;
  public int JJTTAWEEKDAY = 65;
  public int JJTTADURATION = 66;
  public int JJTSALIENCE = 67;
  public int JJTAUTOFOCUS = 68;
  public int JJTSLOWCOMPILE = 69;
  public int JJTRULEVERSION = 70;
  public int JJTNOTFUNCTION = 71;
  public int JJTANDFUNCTION = 72;
  public int JJTORFUNCTION = 73;
  public int JJTASSIGNEDPATTERNCE = 74;
  public int JJTLOGICALCE = 75;
  public int JJTTESTCE = 76;
  public int JJTEXISTSCE = 77;
  public int JJTFORALLCE = 78;
  public int JJTTEMPLATEPATTERNCE = 79;
  public int JJTUNORDEREDLHSFACTBODY = 80;
  public int JJTORDEREDLHSFACTBODY = 81;
  public int JJTLHSSLOT = 82;
  public int JJTSINGLEFIELDWILDCARD = 83;
  public int JJTMULTIFIELDWILDCARD = 84;
  public int JJTCONNECTEDCONSTRAINT = 85;
  public int JJTAMPERSANDCONNECTEDCONSTRAINT = 86;
  public int JJTLINECONNECTEDCONSTRAINT = 87;
  public int JJTTERM = 88;
  public int JJTNEGATION = 89;
  public int JJTCOLON = 90;
  public int JJTEQUALS = 91;
  public int JJTDEFGLOBALCONSTRUCT = 92;
  public int JJTGLOBALASSIGNMENT = 93;
  public int JJTDEFFUNCTIONCONSTRUCT = 94;
  public int JJTFUNCTIONGROUP = 95;
  public int JJTDEFGENERICCONSTRUCT = 96;
  public int JJTPARAMETERRESTRICTION = 97;
  public int JJTWILDCARDPARAMETERRESTRICTION = 98;
  public int JJTQUERY = 99;
  public int JJTTYPEATTRIBUTE = 100;
  public int JJTTYPESPECIFICATION = 101;
  public int JJTALLOWEDCONSTANTATTRIBUTE = 102;
  public int JJTSYMBOLLIST = 103;
  public int JJTSTRINGLIST = 104;
  public int JJTLEXEMELIST = 105;
  public int JJTINTEGERLIST = 106;
  public int JJTFLOATLIST = 107;
  public int JJTNUMBERLIST = 108;
  public int JJTVALUELIST = 109;
  public int JJTRANGEATTRIBUTE = 110;
  public int JJTRANGESPECIFICATION = 111;
  public int JJTCARDINALITYATTRIBUTE = 112;
  public int JJTCARDINALITYSPECIFICATION = 113;
  public int JJTDEFMODULECONSTRUCT = 114;


  public String[] jjtNodeName = {
    "Start",
    "Float",
    "Integer",
    "DateTime",
    "void",
    "Symbol",
    "String",
    "True",
    "Nil",
    "SymbolType",
    "StringType",
    "DateTimeType",
    "LexemeType",
    "BooleanType",
    "IntegerType",
    "LongType",
    "ShortType",
    "FloatType",
    "DoubleType",
    "NumberType",
    "False",
    "Constant",
    "ConstructDescription",
    "SingleVariable",
    "GlobalVariable",
    "MultiVariable",
    "VariableType",
    "AnyFunction",
    "Expression",
    "AssertFunc",
    "Modify",
    "FindFactByFactFunc",
    "RetractFunc",
    "IfElseFunc",
    "WhileFunc",
    "LoopForCountFunc",
    "SwitchCaseFunc",
    "CaseStatement",
    "SwitchDefaults",
    "DeftemplateConstruct",
    "Silent",
    "SlotDefinition",
    "SingleSlotDefinition",
    "MultiSlotDefinition",
    "Attributes",
    "DefaultAttribute",
    "DefaultAttributes",
    "DeriveAttribute",
    "NoneAttribute",
    "DynamicAttribute",
    "ModifyPattern",
    "RHSSlot",
    "RHSPattern",
    "DefruleConstruct",
    "ActionList",
    "Declaration",
    "TemporalValidityDeclaration",
    "TemporalValidity",
    "TAMillisecond",
    "TASecond",
    "TAMinute",
    "TAHour",
    "TADay",
    "TAMonth",
    "TAYear",
    "TAWeekday",
    "TADuration",
    "Salience",
    "AutoFocus",
    "SlowCompile",
    "RuleVersion",
    "NotFunction",
    "AndFunction",
    "OrFunction",
    "AssignedPatternCE",
    "LogicalCE",
    "TestCE",
    "ExistsCE",
    "ForallCE",
    "TemplatePatternCE",
    "UnorderedLHSFactBody",
    "OrderedLHSFactBody",
    "LHSSlot",
    "SingleFieldWildcard",
    "MultiFieldWildcard",
    "ConnectedConstraint",
    "AmpersandConnectedConstraint",
    "LineConnectedConstraint",
    "Term",
    "Negation",
    "Colon",
    "Equals",
    "DefglobalConstruct",
    "GlobalAssignment",
    "DeffunctionConstruct",
    "FunctionGroup",
    "DefgenericConstruct",
    "ParameterRestriction",
    "WildcardParameterRestriction",
    "Query",
    "TypeAttribute",
    "TypeSpecification",
    "AllowedConstantAttribute",
    "SymbolList",
    "StringList",
    "LexemeList",
    "IntegerList",
    "FloatList",
    "NumberList",
    "ValueList",
    "RangeAttribute",
    "RangeSpecification",
    "CardinalityAttribute",
    "CardinalitySpecification",
    "DefmoduleConstruct",
  };
}
