/* Generated By:JJTree: Do not edit this line. SFPRHSPattern.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=SFP,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jamocha.languages.clips.parser;

public class SFPRHSPattern extends SimpleNode {
	public SFPRHSPattern(int id) {
		super(id);
	}

	public SFPRHSPattern(SFPParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(SFPParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
/*
 * JavaCC - OriginalChecksum=4450211573609a3bda17f0279d6f520e (do not edit this
 * line)
 */
