/* Generated By:JJTree: Do not edit this line. SFPRuleVersion.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=SFP,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jamocha.languages.clips.parser;

public class SFPRuleVersion extends SimpleNode {
	public SFPRuleVersion(int id) {
		super(id);
	}

	public SFPRuleVersion(SFPParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(SFPParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
/*
 * JavaCC - OriginalChecksum=93b3016f2f843e0c0cde742059a1cde5 (do not edit this
 * line)
 */
