/* Generated By:JJTree: Do not edit this line. SFPRetractFunc.java */

package org.jamocha.languages.clips.parser;

public class SFPRetractFunc extends SimpleNode {
  public SFPRetractFunc(int id) {
    super(id);
  }

  public SFPRetractFunc(SFPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SFPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
