/* Generated By:JJTree: Do not edit this line. SFPRangeAttribute.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=SFP,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jamocha.languages.clips.parser;

public class SFPRangeAttribute extends SimpleNode {
	public SFPRangeAttribute(int id) {
		super(id);
	}

	public SFPRangeAttribute(SFPParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(SFPParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
/*
 * JavaCC - OriginalChecksum=6f1c709a0b8174f85c95e2b23d1a1bbf (do not edit this
 * line)
 */
