/* Generated By:JJTree: Do not edit this line. SFPSlowCompile.java */

package org.jamocha.languages.clips.parser;

public class SFPSlowCompile extends SimpleNode {
  public SFPSlowCompile(int id) {
    super(id);
  }

  public SFPSlowCompile(SFPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SFPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
