/* Generated By:JJTree: Do not edit this line. SFPStart.java */

package org.jamocha.languages.clips.parser;

public class SFPStart extends SimpleNode {
  public SFPStart(int id) {
    super(id);
  }

  public SFPStart(SFPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SFPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
