/* Generated By:JJTree: Do not edit this line. SFPSingleVariable.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=SFP,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jamocha.languages.clips.parser;

public class SFPSingleVariable extends SimpleNode {
	public SFPSingleVariable(int id) {
		super(id);
	}

	public SFPSingleVariable(SFPParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(SFPParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
/*
 * JavaCC - OriginalChecksum=efcdc884a007732ab64712b45d73a2f0 (do not edit this
 * line)
 */
