/* Generated By:JJTree: Do not edit this line. SFPSymbolType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=SFP,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jamocha.languages.clips.parser;

public class SFPSymbolType extends SimpleNode {
	public SFPSymbolType(int id) {
		super(id);
	}

	public SFPSymbolType(SFPParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(SFPParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
/*
 * JavaCC - OriginalChecksum=22dd07c17ab92510d006b66e61ae87eb (do not edit this
 * line)
 */
