/* Generated By:JJTree: Do not edit this line. SFPShortType.java */

package org.jamocha.languages.clips.parser;

public class SFPShortType extends SimpleNode {
  public SFPShortType(int id) {
    super(id);
  }

  public SFPShortType(SFPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SFPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
