/* Generated By:JJTree: Do not edit this line. SFPTAWeekday.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=SFP,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jamocha.languages.clips.parser;

public class SFPTAWeekday extends SimpleNode {
	public SFPTAWeekday(int id) {
		super(id);
	}

	public SFPTAWeekday(SFPParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(SFPParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
/*
 * JavaCC - OriginalChecksum=cf51da509ad934c50923f45e9e1e32a3 (do not edit this
 * line)
 */
