/* Generated By:JJTree: Do not edit this line. SFPTypeSpecification.java */

package org.jamocha.languages.clips.parser;

public class SFPTypeSpecification extends SimpleNode {
  public SFPTypeSpecification(int id) {
    super(id);
  }

  public SFPTypeSpecification(SFPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SFPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
