/* Generated By:JJTree: Do not edit this line. SFPTypeAttribute.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=SFP,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jamocha.languages.clips.parser;

public class SFPTypeAttribute extends SimpleNode {
	public SFPTypeAttribute(int id) {
		super(id);
	}

	public SFPTypeAttribute(SFPParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(SFPParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
/*
 * JavaCC - OriginalChecksum=3a96514fcadc02181ce3290da304e09d (do not edit this
 * line)
 */
