/* Generated By:JJTree: Do not edit this line. SFPTAYear.java */

package org.jamocha.languages.clips.parser;

public class SFPTAYear extends SimpleNode {
  public SFPTAYear(int id) {
    super(id);
  }

  public SFPTAYear(SFPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SFPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
