/* Generated By:JJTree: Do not edit this line. SFPTAYear.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=SFP,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jamocha.languages.clips.parser;

public class SFPTAYear extends SimpleNode {
	public SFPTAYear(int id) {
		super(id);
	}

	public SFPTAYear(SFPParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(SFPParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
/*
 * JavaCC - OriginalChecksum=b836dd2617c79eee6fc89ed9a4e11051 (do not edit this
 * line)
 */
