/* Generated By:JJTree: Do not edit this line. SFPTypeSpecification.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=SFP,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jamocha.languages.clips.parser;

public class SFPTypeSpecification extends SimpleNode {
	public SFPTypeSpecification(int id) {
		super(id);
	}

	public SFPTypeSpecification(SFPParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(SFPParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
/*
 * JavaCC - OriginalChecksum=609ece7211f204fba3c48d234e60d0cc (do not edit this
 * line)
 */
