/* Generated By:JJTree: Do not edit this line. SFPTemporalValidity.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=SFP,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jamocha.languages.clips.parser;

public class SFPTemporalValidity extends SimpleNode {
	public SFPTemporalValidity(int id) {
		super(id);
	}

	public SFPTemporalValidity(SFPParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(SFPParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
/*
 * JavaCC - OriginalChecksum=8a171f103d4cabff591ec450873929ca (do not edit this
 * line)
 */
