/* Generated By:JJTree: Do not edit this line. COOLDefclassConstruct.java */

public class COOLDefclassConstruct extends ConstructNode {

	/** List of class names
	 */
	protected java.util.ArrayList<String> classlist;

	/** Adds a class name to the list
	 *@param classname classname to be added
	 */
	public void addClassname(String classname) { this.classlist.add(classname); }

	/** Gets Method Index (cf. clipsbasic programmers guide section 8.4.2)
	 *@return method index
	 */
	public String[] getClasslist()
	{
		String[] classarray = new String[this.classlist.size()];
		return this.classlist.toArray(classarray);
	}

	public COOLDefclassConstruct(int id) {
		super(id);
		this.classlist = new java.util.ArrayList<String>();
	}

	public COOLDefclassConstruct(COOL p, int id) {
		super(p, id);
		this.classlist = new java.util.ArrayList<String>();
	}

	public String toString() {
		String classes = "";
		for( String s : this.classlist ) classes += s + " ";
		return "defclass \"" + name + "\" (" + doc + "), classes: " + classes;
	}

}
