/* Generated By:JJTree: Do not edit this line. COOLAllowedType.java */

public class COOLAllowedType extends SimpleNode {
  public COOLAllowedType(int id) {
    super(id);
  }

  public COOLAllowedType(COOL p, int id) {
    super(p, id);
  }

}
