/* Generated By:JJTree: Do not edit this line. COOLSourceFacet.java */

public class COOLSourceFacet extends SimpleNode {
  public COOLSourceFacet(int id) {
    super(id);
  }

  public COOLSourceFacet(COOL p, int id) {
    super(p, id);
  }

}
