/* Generated By:JJTree: Do not edit this line. COOLMessageHandler.java */

public class COOLMessageHandler extends SimpleNode {
  public COOLMessageHandler(int id) {
    super(id);
  }

  public COOLMessageHandler(COOL p, int id) {
    super(p, id);
  }

}
