/* Generated By:JJTree: Do not edit this line. COOLMultiFieldWildcard.java */

public class COOLMultiFieldWildcard extends SimpleNode {
  public COOLMultiFieldWildcard(int id) {
    super(id);
  }

  public COOLMultiFieldWildcard(COOL p, int id) {
    super(p, id);
  }

}
