/* Generated By:JJTree: Do not edit this line. COOLValueList.java */

public class COOLValueList extends SimpleNode {
  public COOLValueList(int id) {
    super(id);
  }

  public COOLValueList(COOL p, int id) {
    super(p, id);
  }

}
