/* Generated By:JJTree: Do not edit this line. COOLStorageFacet.java */

public class COOLStorageFacet extends SimpleNode {
  public COOLStorageFacet(int id) {
    super(id);
  }

  public COOLStorageFacet(COOL p, int id) {
    super(p, id);
  }

}
