/* Generated By:JJTree: Do not edit this line. COOLSlot.java */

public class COOLSlot extends SimpleNode {
  public COOLSlot(int id) {
    super(id);
  }

  public COOLSlot(COOL p, int id) {
    super(p, id);
  }

}
