/* Generated By:JJTree: Do not edit this line. CLIPS_SLInteger.java */
/** AST Node representing an Integer.
	@author jjTree
	@author Ory Chowaw-Liebman
*/

public class COOLInteger extends SimpleNode {

	private long value;

	public void setName(String n) 
	{ 
		name = n; 
		value = Long.parseLong( n ) ;
	}
	public String getName() { return name; }

	public COOLInteger(int id) {
		super(id);
	}

	public COOLInteger(COOL p, int id) {
		super(p, id);
	}
	
	public String toString() {
		return "Integer: " + name;
	}
	
	public boolean compareTree(SimpleNode n)
	{
		int i;
		// Do both nodes have the same id?
		if (id!=n.getId()) return false;
		// Do both nodes have the same contents?
		if (execute().toInteger()!=n.execute().toInteger()) return false;
		// Yes, they do
		return true;
	}
	
	public CLIPSData execute() {
		return new CLIPSInteger(value); 
	}
}
