/* Generated By:JJTree: Do not edit this line. COOLPatternMatchRole.java */

public class COOLPatternMatchRole extends SimpleNode {
  public COOLPatternMatchRole(int id) {
    super(id);
  }

  public COOLPatternMatchRole(COOL p, int id) {
    super(p, id);
  }

}
