/* Generated By:JJTree: Do not edit this line. COOLTypeSpecification.java */

public class COOLTypeSpecification extends SimpleNode {
  public COOLTypeSpecification(int id) {
    super(id);
  }

  public COOLTypeSpecification(COOL p, int id) {
    super(p, id);
  }

}
