/* Generated By:JJTree: Do not edit this line. COOLForallCE.java */

public class COOLForallCE extends SimpleNode {
  public COOLForallCE(int id) {
    super(id);
  }

  public COOLForallCE(COOL p, int id) {
    super(p, id);
  }

}
