/* Generated By:JJTree: Do not edit this line. CLIPS_SLFunctionCall.java */
/** AST Node representing a Function Call.
	@author jjTree
	@author Ory Chowaw-Liebman
*/

public class COOLFunctionCall extends SimpleNode {

	public COOLFunctionCall(int id) {
		super(id);
	}

	public COOLFunctionCall(COOL p, int id) {
		super(p, id);
	}
	
	public String toString() {
		return "Function \"" + name + "\"";
	}

	public CLIPSData execute() {
		// if function name is not known, we should throw an exception
		CLIPSFunction func=parser.getFunction(name);
		if (func==null) return new CLIPSBool(false);
		int i,numkids=jjtGetNumChildren();
		CLIPSData [] params = new CLIPSData[numkids];
		
		// Get Subtree results
		for (i=0;i<numkids;i++)
		{
			Node n=jjtGetChild(i);
			params[i]=n.execute();
		}
		// Call Function
		return func.execute(params);
	}
}
