/* Generated By:JJTree: Do not edit this line. CLIPS_SLStart.java */

public class COOLStart extends SimpleNode {
  public COOLStart(int id) {
    super(id);
  }

  public COOLStart(COOL p, int id) {
    super(p, id);
  }

}
