/* Generated By:JJTree: Do not edit this line. COOLConstraintAttribute.java */

public class COOLConstraintAttribute extends SimpleNode {
  public COOLConstraintAttribute(int id) {
    super(id);
  }

  public COOLConstraintAttribute(COOL p, int id) {
    super(p, id);
  }

}
