/* Generated By:JJTree: Do not edit this line. COOLFloatList.java */

public class COOLFloatList extends SimpleNode {
  public COOLFloatList(int id) {
    super(id);
  }

  public COOLFloatList(COOL p, int id) {
    super(p, id);
  }

}
