/* Generated By:JJTree&JavaCC: Do not edit this line. COOLConstants.java */
public interface COOLConstants {

  int EOF = 0;
  int COMMENT_TEXT = 7;
  int END_COMMENT = 8;
  int LBRACE = 9;
  int RBRACE = 10;
  int GE1 = 11;
  int INTEGER = 12;
  int FLOAT = 13;
  int EXPONENT = 14;
  int STRING = 15;
  int INSTANCE = 16;
  int VARSYMBOL = 17;
  int SINGLEVAR = 18;
  int MULTIVAR = 19;
  int GLOBALVAR = 20;
  int DEFFACTS = 21;
  int DEFTEMPLATE = 22;
  int DEFRULE = 23;
  int DEFFUNCTION = 24;
  int DEFGENERIC = 25;
  int DEFMETHOD = 26;
  int DEFCLASS = 27;
  int DEFGLOBAL = 28;
  int DEFAULT_ATR = 29;
  int DYNAMIC_ATR = 30;
  int ATR_DEFAULT = 31;
  int ATR_DERIVE = 32;
  int ATR_NONE = 33;
  int SLOT = 34;
  int SINGLE_SLOT = 35;
  int MULTISLOT = 36;
  int ARROW = 37;
  int DECLARE = 38;
  int SALIENCE = 39;
  int AUTOFOCUS = 40;
  int TYPE = 41;
  int TRUE = 42;
  int FALSE = 43;
  int NOT = 44;
  int AND = 45;
  int OR = 46;
  int LOGICAL = 47;
  int TEST = 48;
  int EXISTS = 49;
  int FORALL = 50;
  int OBJECT = 51;
  int IS_A = 52;
  int NAME = 53;
  int ASSIGN = 54;
  int SFWILDCARD = 55;
  int MFWILDCARD = 56;
  int TILDE = 57;
  int AMPERSAND = 58;
  int LINE = 59;
  int COLON = 60;
  int EQUALS = 61;
  int VARIABLE_TYPE = 62;
  int SYMBOL_TYPE = 63;
  int STRING_TYPE = 64;
  int LEXEME_TYPE = 65;
  int INTEGER_TYPE = 66;
  int FLOAT_TYPE = 67;
  int NUMBER_TYPE = 68;
  int INSTANCE_NAME_TYPE = 69;
  int INSTANCE_ADDRESS_TYPE = 70;
  int INSTANCE_TYPE = 71;
  int EXTERNAL_ADDRESS_TYPE = 72;
  int FACT_ADDRESS_TYPE = 73;
  int ALLOWED_SYMBOLS = 74;
  int ALLOWED_STRINGS = 75;
  int ALLOWED_LEXEMES = 76;
  int ALLOWED_INTEGERS = 77;
  int ALLOWED_FLOATS = 78;
  int ALLOWED_NUMBERS = 79;
  int ALLOWED_INSTANCES = 80;
  int ALLOWED_CLASSES = 81;
  int ALLOWED_VALUES = 82;
  int RANGE = 83;
  int CARDINALITY = 84;
  int ROLE = 85;
  int CONCRETE = 86;
  int ABSTRACT = 87;
  int PATTERN_MATCH = 88;
  int REACTIVE = 89;
  int NON_REACTIVE = 90;
  int STORAGE = 91;
  int LOCAL = 92;
  int SHARED = 93;
  int ACCESS = 94;
  int READ_WRITE = 95;
  int READ_ONLY = 96;
  int READ = 97;
  int WRITE = 98;
  int INITIALIZE_ONLY = 99;
  int PROPAGATION = 100;
  int INHERIT = 101;
  int NO_INHERIT = 102;
  int SOURCE = 103;
  int EXCLUSIVE = 104;
  int COMPOSITE = 105;
  int VISIBILITY = 106;
  int PRIVATE = 107;
  int PUBLIC = 108;
  int CREATE_ACCESSOR = 109;
  int OVERRIDE_MESSAGE = 110;
  int MESSAGE_HANDLER = 111;
  int PRIMARY = 112;
  int AROUND = 113;
  int BEFORE = 114;
  int AFTER = 115;
  int SYMBOL = 116;

  int DEFAULT = 0;
  int IN_COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\";;\"",
    "<token of kind 6>",
    "<COMMENT_TEXT>",
    "<END_COMMENT>",
    "\"(\"",
    "\")\"",
    "\">=\"",
    "<INTEGER>",
    "<FLOAT>",
    "<EXPONENT>",
    "<STRING>",
    "<INSTANCE>",
    "<VARSYMBOL>",
    "<SINGLEVAR>",
    "<MULTIVAR>",
    "<GLOBALVAR>",
    "\"deffacts\"",
    "\"deftemplate\"",
    "\"defrule\"",
    "\"deffunction\"",
    "\"defgeneric\"",
    "\"defmethod\"",
    "\"defclass\"",
    "\"defglobal\"",
    "\"default\"",
    "\"default-dynamic\"",
    "\"?DEFAULT\"",
    "\"?DERIVE\"",
    "\"?NONE\"",
    "\"slot\"",
    "\"single-slot\"",
    "\"multislot\"",
    "\"=>\"",
    "\"declare\"",
    "\"salience\"",
    "\"auto-focus\"",
    "\"type\"",
    "<TRUE>",
    "<FALSE>",
    "\"not\"",
    "\"and\"",
    "\"or\"",
    "\"logical\"",
    "\"test\"",
    "\"exists\"",
    "\"forall\"",
    "\"object\"",
    "\"is-a\"",
    "\"name\"",
    "\"<-\"",
    "\"?\"",
    "\"$?\"",
    "\"~\"",
    "\"&\"",
    "\"|\"",
    "\":\"",
    "\"=\"",
    "\"?VARIABLE\"",
    "\"SYMBOL\"",
    "\"STRING\"",
    "\"LEXEME\"",
    "\"INTEGER\"",
    "\"FLOAT\"",
    "\"NUMBER\"",
    "\"INSTANCE-NAME\"",
    "\"INSTANCE-ADDRESS\"",
    "\"INSTANCE\"",
    "\"EXTERNAL-ADDRESS\"",
    "\"FACT-ADDRESS\"",
    "\"allowed-symbols\"",
    "\"allowed-strings\"",
    "\"allowed-lexemes\"",
    "\"allowed-integers\"",
    "\"allowed-floats\"",
    "\"allowed-numbers\"",
    "\"allowed-instances\"",
    "\"allowed-classes\"",
    "\"allowed-values\"",
    "\"range\"",
    "\"cardinality\"",
    "\"role\"",
    "\"concrete\"",
    "\"abstract\"",
    "\"pattern-match\"",
    "\"reactive\"",
    "\"non-reactive\"",
    "\"storage\"",
    "\"local\"",
    "\"shared\"",
    "\"access\"",
    "\"read-write\"",
    "\"read-only\"",
    "\"read\"",
    "\"write\"",
    "\"initialize-only\"",
    "\"propagation\"",
    "\"inherit\"",
    "\"no-inherit\"",
    "\"source\"",
    "\"exclusive\"",
    "\"composite\"",
    "\"visibility\"",
    "\"private\"",
    "\"public\"",
    "\"create-accessor\"",
    "\"override-message\"",
    "\"message-handler\"",
    "\"primary\"",
    "\"around\"",
    "\"before\"",
    "\"after\"",
    "<SYMBOL>",
  };

}
