/* Generated By:JJTree: Do not edit this line. COOLAssignedPatternCE.java */

public class COOLAssignedPatternCE extends SimpleNode {
  public COOLAssignedPatternCE(int id) {
    super(id);
  }

  public COOLAssignedPatternCE(COOL p, int id) {
    super(p, id);
  }

}
