/* Generated By:JJTree: Do not edit this line. ./COOLTreeConstants.java */

public interface COOLTreeConstants
{
  public int JJTSTART = 0;
  public int JJTFLOAT = 1;
  public int JJTINTEGER = 2;
  public int JJTVOID = 3;
  public int JJTSYMBOL = 4;
  public int JJTSTRING = 5;
  public int JJTINSTANCE = 6;
  public int JJTSINGLEVARIABLE = 7;
  public int JJTGLOBALVARIABLE = 8;
  public int JJTMULTIVARIABLE = 9;
  public int JJTFUNCTIONCALL = 10;
  public int JJTDEFFACTSCONSTRUCT = 11;
  public int JJTDEFTEMPLATECONSTRUCT = 12;
  public int JJTSINGLESLOTDEFINITION = 13;
  public int JJTMULTISLOTDEFINITION = 14;
  public int JJTDEFAULTATTRIBUTE = 15;
  public int JJTDYNAMICATTRIBUTE = 16;
  public int JJTORDEREDRHSPATTERN = 17;
  public int JJTTEMPLATERHSPATTERN = 18;
  public int JJTSINGLEFIELDRHSSLOT = 19;
  public int JJTMULTIFIELDRHSSLOT = 20;
  public int JJTDEFRULECONSTRUCT = 21;
  public int JJTCELIST = 22;
  public int JJTACTIONLIST = 23;
  public int JJTCELIST2 = 24;
  public int JJTDECLARATION = 25;
  public int JJTRULEPROPERTY = 26;
  public int JJTBOOLEANSYMBOL = 27;
  public int JJTBOOLEANFUNCTION = 28;
  public int JJTASSIGNEDPATTERNCE = 29;
  public int JJTLOGICALCE = 30;
  public int JJTTESTCE = 31;
  public int JJTEXISTSCE = 32;
  public int JJTFORALLCE = 33;
  public int JJTORDEREDPATTERNCE = 34;
  public int JJTTEMPLATEPATTERNCE = 35;
  public int JJTOBJECTPATTERNCE = 36;
  public int JJTATTRIBUTECONSTRAINT = 37;
  public int JJTLHSSLOT = 38;
  public int JJTSINGLEFIELDWILDCARD = 39;
  public int JJTMULTIFIELDWILDCARD = 40;
  public int JJTCONNECTEDCONSTRAINT = 41;
  public int JJTTERM = 42;
  public int JJTDEFGLOBALCONSTRUCT = 43;
  public int JJTGLOBALASSIGNMENT = 44;
  public int JJTDEFFUNCTIONCONSTRUCT = 45;
  public int JJTPARAMETERLIST = 46;
  public int JJTDEFGENERICCONSTRUCT = 47;
  public int JJTDEFMETHODCONSTRUCT = 48;
  public int JJTPARAMETERRESTRICTION = 49;
  public int JJTWILDCARDPARAMETERRESTRICTION = 50;
  public int JJTTYPE = 51;
  public int JJTQUERY = 52;
  public int JJTDEFCLASSCONSTRUCT = 53;
  public int JJTROLE = 54;
  public int JJTPATTERNMATCHROLE = 55;
  public int JJTSLOT = 56;
  public int JJTDEFAULTFACET = 57;
  public int JJTSTORAGEFACET = 58;
  public int JJTACCESSFACET = 59;
  public int JJTPROPAGATIONFACET = 60;
  public int JJTSOURCEFACET = 61;
  public int JJTPATTERNMATCHFACET = 62;
  public int JJTVISIBILITYFACET = 63;
  public int JJTCREATEACCESSORFACET = 64;
  public int JJTOVERRIDEMESSAGEFACET = 65;
  public int JJTHANDLERDOCUMENTATION = 66;
  public int JJTHANDLERTYPE = 67;
  public int JJTCONSTRAINTATTRIBUTE = 68;
  public int JJTTYPEATTRIBUTE = 69;
  public int JJTTYPESPECIFICATION = 70;
  public int JJTALLOWEDCONSTANTATTRIBUTE = 71;
  public int JJTSYMBOLLIST = 72;
  public int JJTSTRINGLIST = 73;
  public int JJTLEXEMELIST = 74;
  public int JJTINTEGERLIST = 75;
  public int JJTFLOATLIST = 76;
  public int JJTNUMBERLIST = 77;
  public int JJTINSTANCELIST = 78;
  public int JJTCLASSNAMELIST = 79;
  public int JJTVALUELIST = 80;
  public int JJTRANGEATTRIBUTE = 81;
  public int JJTRANGESPECIFICATION = 82;
  public int JJTCARDINALITYATTRIBUTE = 83;
  public int JJTCARDINALITYSPECIFICATION = 84;


  public String[] jjtNodeName = {
    "Start",
    "Float",
    "Integer",
    "void",
    "Symbol",
    "String",
    "Instance",
    "SingleVariable",
    "GlobalVariable",
    "MultiVariable",
    "FunctionCall",
    "DefFactsConstruct",
    "DefTemplateConstruct",
    "SingleSlotDefinition",
    "MultislotDefinition",
    "DefaultAttribute",
    "DynamicAttribute",
    "OrderedRHSPattern",
    "TemplateRHSPattern",
    "SingleFieldRHSSlot",
    "MultifieldRHSSlot",
    "DefruleConstruct",
    "CEList",
    "ActionList",
    "CEList2",
    "Declaration",
    "RuleProperty",
    "BooleanSymbol",
    "BooleanFunction",
    "AssignedPatternCE",
    "LogicalCE",
    "TestCE",
    "ExistsCE",
    "ForallCE",
    "OrderedPatternCE",
    "TemplatePatternCE",
    "ObjectPatternCE",
    "AttributeConstraint",
    "LHSSlot",
    "SingleFieldWildcard",
    "MultiFieldWildcard",
    "ConnectedConstraint",
    "Term",
    "DefglobalConstruct",
    "GlobalAssignment",
    "DeffunctionConstruct",
    "ParameterList",
    "DefgenericConstruct",
    "DefmethodConstruct",
    "ParameterRestriction",
    "WildcardParameterRestriction",
    "Type",
    "Query",
    "DefclassConstruct",
    "Role",
    "PatternMatchRole",
    "Slot",
    "DefaultFacet",
    "StorageFacet",
    "AccessFacet",
    "PropagationFacet",
    "SourceFacet",
    "PatternMatchFacet",
    "VisibilityFacet",
    "CreateAccessorFacet",
    "OverrideMessageFacet",
    "HandlerDocumentation",
    "HandlerType",
    "ConstraintAttribute",
    "TypeAttribute",
    "TypeSpecification",
    "AllowedConstantAttribute",
    "SymbolList",
    "StringList",
    "LexemeList",
    "IntegerList",
    "FloatList",
    "NumberList",
    "InstanceList",
    "ClassNameList",
    "ValueList",
    "RangeAttribute",
    "RangeSpecification",
    "CardinalityAttribute",
    "CardinalitySpecification",
  };
}
