/* Generated By:JJTree: Do not edit this line. COOLOverrideMessageFacet.java */

public class COOLOverrideMessageFacet extends SimpleNode {
  public COOLOverrideMessageFacet(int id) {
    super(id);
  }

  public COOLOverrideMessageFacet(COOL p, int id) {
    super(p, id);
  }

}
