/* Generated By:JJTree: Do not edit this line. COOLActionList.java */

public class COOLActionList extends SimpleNode {
  public COOLActionList(int id) {
    super(id);
  }

  public COOLActionList(COOL p, int id) {
    super(p, id);
  }

}
