/* Generated By:JJTree: Do not edit this line. COOLDynamicAttribute.java */

public class COOLDynamicAttribute extends SimpleNode {
  public COOLDynamicAttribute(int id) {
    super(id);
  }

  public COOLDynamicAttribute(COOL p, int id) {
    super(p, id);
  }

}
