/* Generated By:JJTree: Do not edit this line. COOLCEList2.java */

public class COOLCEList2 extends SimpleNode {
  public COOLCEList2(int id) {
    super(id);
  }

  public COOLCEList2(COOL p, int id) {
    super(p, id);
  }

}
