/* Generated By:JJTree: Do not edit this line. COOLLHSSlot.java */

public class COOLLHSSlot extends SimpleNode {
  public COOLLHSSlot(int id) {
    super(id);
  }

  public COOLLHSSlot(COOL p, int id) {
    super(p, id);
  }

}
