/* Generated By:JJTree: Do not edit this line. COOLDefaultAttribute.java */

public class COOLDefaultAttribute extends SimpleNode {
	final static int T_UNDEF = 0;
	final static int T_DERIVE = 1;
	final static int T_NONE = 2;
	
	protected int type;
	
	public COOLDefaultAttribute(int id) {
		super(id);
	}

	public COOLDefaultAttribute(COOL p, int id) {
		super(p, id);
	}

	public int getType() { return type; };

	public void setType(int t)
	{
		switch(t)
		{
		case T_DERIVE: 
			name="derive";
			type=t;
			break;
		case T_NONE: 
			name="none";
			type=t;
			break;
		default: 
			name="undef";
			type=T_UNDEF;
			break;
		}
	}
}
