/* Generated By:JJTree: Do not edit this line. COOLLogicalCE.java */

public class COOLLogicalCE extends SimpleNode {
  public COOLLogicalCE(int id) {
    super(id);
  }

  public COOLLogicalCE(COOL p, int id) {
    super(p, id);
  }

}
