/* Generated By:JJTree: Do not edit this line. COOLStringList.java */

public class COOLStringList extends SimpleNode {
  public COOLStringList(int id) {
    super(id);
  }

  public COOLStringList(COOL p, int id) {
    super(p, id);
  }

}
