/* Generated By:JJTree: Do not edit this line. COOLLexemeList.java */

public class COOLLexemeList extends SimpleNode {
  public COOLLexemeList(int id) {
    super(id);
  }

  public COOLLexemeList(COOL p, int id) {
    super(p, id);
  }

}
