/* Generated By:JJTree: Do not edit this line. COOLDeffunctionConstruct.java */

import org.jamocha.parser.*;
import org.jamocha.rete.*;
import java.util.ArrayList;

public class COOLDeffunctionConstruct extends ConstructNode {

	private DefFunctionTree deffunc=new DefFunctionTree();
	private boolean varargs;
	
	public COOLDeffunctionConstruct(int id) {
		super(id);
	}
	
	public COOLDeffunctionConstruct(COOL p, int id) {
		super(p, id);
	}
	
	public void setName(String n) 
	{ 
		name = n; 
		deffunc.setName(n);
	}

	public void setDocString(String ds)
	{ 
		doc=ds; 
		deffunc.setDocString(ds);
	}

	public String toString() {
		return "deffunction \"" + name + " (" + doc + ")";
	}
	
	public void setFunctionActions(Node n)
	{	deffunc.setAction(n);	};
	
	public void SetFunctionParams(ArrayList<String> list)
	{
		String names[]=new String[list.size()];
		//int i;
		//for (i=0;i<list.size();i++) names[i]=list.get(i);
		list.toArray(names);
		deffunc.setLocals(names,varargs);
	}
	
	public void hasMultiVars(boolean has)
	{ varargs=true; }
	
	public JamochaValue execute() //throws EvaluationException
	{
		parser.setFunction(deffunc);
		return JamochaValue.TRUE;
	};
	
}
