/* Generated By:JJTree: Do not edit this line. COOLSingleFieldLHSSlot.java */

public class COOLSingleFieldLHSSlot extends SimpleNode {
  public COOLSingleFieldLHSSlot(int id) {
    super(id);
  }

  public COOLSingleFieldLHSSlot(COOL p, int id) {
    super(p, id);
  }

}
