/* Generated By:JJTree: Do not edit this line. COOLPortItem.java */

public class COOLPortItem extends SimpleNode {
  public COOLPortItem(int id) {
    super(id);
  }

  public COOLPortItem(COOL p, int id) {
    super(p, id);
  }

}
