/* Generated By:JJTree: Do not edit this line. COOLBooleanFunction.java */

// Use member CLIPSBool for return value??
public class COOLBooleanFunction extends SimpleNode {
	public final static int OP_UNDEF = 0;
	public final static int OP_NOT = 1;
	public final static int OP_AND = 2;
	public final static int OP_OR = 3;
	
	protected int type;
		
	public COOLBooleanFunction(int id) {
		super(id);
		setType(OP_UNDEF);
	}
	
	public COOLBooleanFunction(COOL p, int id) {
		super(p, id);
		setType(OP_UNDEF);
	}

	public void setType(int t)
	{
		switch(t)
		{
		case OP_NOT:
			setName("not");
			type=t;
			break;
		case OP_AND:
			setName("and");
			type=t;
			break;
		case OP_OR:
			setName("or");
			type=t;
			break;
		default: 
			setName("undef");
			type=OP_UNDEF; 
			break;
		}
	}
	
	public int getType() { return type; } 
	
	public CLIPSData execute()
	{
		int i;
		switch(type)
		{
		case OP_NOT: 
			return new CLIPSBool(!jjtGetChild(0).execute().toBool());
		case OP_AND:
			for (i=0;i<jjtGetNumChildren();i++)
				if (!jjtGetChild(0).execute().toBool()) return new CLIPSBool(false);
			return new CLIPSBool(true);
		case OP_OR:
			for (i=0;i<jjtGetNumChildren();i++)
				if (jjtGetChild(0).execute().toBool()) return new CLIPSBool(true);
			return new CLIPSBool(false);
		default: 
			return new CLIPSBool(false);
		}
	}

}
