/* Generated By:JJTree: Do not edit this line. COOLParameterList.java */

public class COOLParameterList extends SimpleNode {
  public COOLParameterList(int id) {
    super(id);
  }

  public COOLParameterList(COOL p, int id) {
    super(p, id);
  }

}
