/* Generated By:JJTree: Do not edit this line. COOLTypeAttribute.java */

public class COOLTypeAttribute extends SimpleNode {
  public COOLTypeAttribute(int id) {
    super(id);
  }

  public COOLTypeAttribute(COOL p, int id) {
    super(p, id);
  }

}
