/* Generated By:JJTree: Do not edit this line. SLAtomicFormula.java */

package org.jamocha.parser.sl;

public class SLAtomicFormula extends SimpleNode {
  public SLAtomicFormula(int id) {
    super(id);
  }

  public SLAtomicFormula(SLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
