/* Generated By:JJTree: Do not edit this line. SLBinaryTermOp.java */

package org.jamocha.parser.sl;

public class SLBinaryTermOp extends SimpleNode {
  public SLBinaryTermOp(int id) {
    super(id);
  }

  public SLBinaryTermOp(SLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
