/* Generated By:JJTree: Do not edit this line. SLModalOp.java */

package org.jamocha.parser.sl;

public class SLModalOp extends SimpleNode {
  public SLModalOp(int id) {
    super(id);
  }

  public SLModalOp(SLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
