/* Generated By:JJTree: Do not edit this line. /Users/alex/Documents/workspace/Jamocha/src/main/org/jamocha/parser/sl/SLParserTreeConstants.java */

package org.jamocha.parser.sl;

public interface SLParserTreeConstants
{
  public int JJTCONTENT = 0;
  public int JJTCONTENTEXPRESSION = 1;
  public int JJTPROPOSITION = 2;
  public int JJTWFF = 3;
  public int JJTVOID = 4;
  public int JJTIDENTIFYINGEXPRESSION = 5;
  public int JJTFUNCTIONALTERMWITHTERMORIE = 6;
  public int JJTFUNCTIONALTERMWITHPARAMETER = 7;
  public int JJTACTIONEXPRESSION = 8;
  public int JJTAGENT = 9;
  public int JJTSETORSEQUENCE = 10;
  public int JJTPARAMETER = 11;
  public int JJTUNARYLOGICALOP = 12;
  public int JJTBINARYLOGICALOP = 13;
  public int JJTBINARYTERMOP = 14;
  public int JJTQUANTIFIER = 15;
  public int JJTMODALOP = 16;
  public int JJTACTIONOP = 17;
  public int JJTREFERENTIALOP = 18;
  public int JJTPROPOSITIONSYMBOL = 19;
  public int JJTPREDICATESYMBOL = 20;
  public int JJTFUNCTIONSYMBOL = 21;
  public int JJTBOOLEANSYMBOL = 22;
  public int JJTSTRING = 23;
  public int JJTINTEGER = 24;
  public int JJTFLOAT = 25;
  public int JJTDATETIME = 26;
  public int JJTVARIABLE = 27;
  public int JJTPARAMETERNAME = 28;


  public String[] jjtNodeName = {
    "Content",
    "ContentExpression",
    "Proposition",
    "Wff",
    "void",
    "IdentifyingExpression",
    "FunctionalTermWithTermOrIE",
    "FunctionalTermWithParameter",
    "ActionExpression",
    "Agent",
    "SetOrSequence",
    "Parameter",
    "UnaryLogicalOp",
    "BinaryLogicalOp",
    "BinaryTermOp",
    "Quantifier",
    "ModalOp",
    "ActionOp",
    "ReferentialOp",
    "PropositionSymbol",
    "PredicateSymbol",
    "FunctionSymbol",
    "BooleanSymbol",
    "String",
    "Integer",
    "Float",
    "DateTime",
    "Variable",
    "ParameterName",
  };
}
