/* Generated By:JJTree&JavaCC: Do not edit this line. SLParserConstants.java */
package org.jamocha.parser.sl;

public interface SLParserConstants {

  int EOF = 0;
  int STRING = 33;
  int WORD = 34;
  int PARAMETER_NAME = 35;
  int VARIABLE_IDENTIFIER = 36;
  int SIGN = 37;
  int INTEGER = 38;
  int FLOAT = 39;
  int FLOATMANTISSA = 40;
  int FLOATEXPONENT = 41;
  int DIGIT = 42;
  int HEXDIGIT = 43;
  int STRING_LITERAL = 44;
  int DATETIME = 45;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"(\"",
    "\")\"",
    "\"not\"",
    "\"and\"",
    "\"or\"",
    "\"implies\"",
    "\"equiv\"",
    "\"forall\"",
    "\"exists\"",
    "\"B\"",
    "\"U\"",
    "\"PG\"",
    "\"I\"",
    "\"feasible\"",
    "\"done\"",
    "\"true\"",
    "\"false\"",
    "\"=\"",
    "\"result\"",
    "\"iota\"",
    "\"any\"",
    "\"all\"",
    "\"action\"",
    "\"|\"",
    "\";\"",
    "\"sequence\"",
    "\"set\"",
    "<STRING>",
    "<WORD>",
    "<PARAMETER_NAME>",
    "<VARIABLE_IDENTIFIER>",
    "<SIGN>",
    "<INTEGER>",
    "<FLOAT>",
    "<FLOATMANTISSA>",
    "<FLOATEXPONENT>",
    "<DIGIT>",
    "<HEXDIGIT>",
    "<STRING_LITERAL>",
    "<DATETIME>",
  };

}
