/* Generated By:JJTree&JavaCC: Do not edit this line. SLParserConstants.java */
package org.jamocha.parser.sl;

public interface SLParserConstants {

  int EOF = 0;
  int TRUE = 6;
  int FALSE = 7;
  int NOT = 8;
  int AND = 9;
  int OR = 10;
  int IMPLIES = 11;
  int EQUIV = 12;
  int EQUAL = 13;
  int RESULT = 14;
  int FORALL = 15;
  int EXISTS = 16;
  int MODAL_B = 17;
  int MODAL_U = 18;
  int MODAL_PG = 19;
  int MODAL_I = 20;
  int FEASIBLE = 21;
  int DONE = 22;
  int IOTA = 23;
  int ANY = 24;
  int ALL = 25;
  int SEQUENCE = 26;
  int SET = 27;
  int ACTION = 28;
  int PIPE = 29;
  int SEMICOLON = 30;
  int LBRACE = 31;
  int RBRACE = 32;
  int STRING = 33;
  int WORD = 34;
  int PARAMETER_NAME = 35;
  int VARIABLE_IDENTIFIER = 36;
  int SIGN = 37;
  int INTEGER = 38;
  int FLOAT = 39;
  int FLOATMANTISSA = 40;
  int FLOATEXPONENT = 41;
  int DIGIT = 42;
  int HEXDIGIT = 43;
  int STRING_LITERAL = 44;
  int DATETIME = 45;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"true\"",
    "\"false\"",
    "\"not\"",
    "\"and\"",
    "\"or\"",
    "\"implies\"",
    "\"equiv\"",
    "\"=\"",
    "\"result\"",
    "\"forall\"",
    "\"exists\"",
    "\"B\"",
    "\"U\"",
    "\"PG\"",
    "\"I\"",
    "\"feasible\"",
    "\"done\"",
    "\"iota\"",
    "\"any\"",
    "\"all\"",
    "\"sequence\"",
    "\"set\"",
    "\"action\"",
    "\"|\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "<STRING>",
    "<WORD>",
    "<PARAMETER_NAME>",
    "<VARIABLE_IDENTIFIER>",
    "<SIGN>",
    "<INTEGER>",
    "<FLOAT>",
    "<FLOATMANTISSA>",
    "<FLOATEXPONENT>",
    "<DIGIT>",
    "<HEXDIGIT>",
    "<STRING_LITERAL>",
    "<DATETIME>",
  };

}
