/* Generated By:JJTree: Do not edit this line. SLString.java */

package org.jamocha.parser.sl;

public class SLString extends SimpleNode {
  public SLString(int id) {
    super(id);
  }

  public SLString(SLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
