/* Generated By:JJTree: Do not edit this line. SLProposition.java */

package org.jamocha.parser.slp;

public class SLProposition extends SimpleNode {
  public SLProposition(int id) {
    super(id);
  }

  public SLProposition(SLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
