/* Generated By:JJTree: Do not edit this line. SLVariable.java */

package org.jamocha.parser.slp;

public class SLVariable extends SimpleNode {
  public SLVariable(int id) {
    super(id);
  }

  public SLVariable(SLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
