(unwatch compilations)
;(conserve-mem on)
(load clipsfiles/weaver/weaver0.clp)
(load clipsfiles/weaver/weaver1.clp)
(load clipsfiles/weaver/weaver2.clp)
(load clipsfiles/weaver/weaver3.clp)
(load clipsfiles/weaver/weaver4.clp)
(load clipsfiles/weaver/weaver5.clp)
(load clipsfiles/weaver/weaver6.clp)
(load clipsfiles/weaver/weaver7.clp)
(load clipsfiles/weaver/weaver8.clp)
(load clipsfiles/weaver/weaver9.clp)
(load clipsfiles/weaver/weaver10.clp)
(load clipsfiles/weaver/weaver11.clp)
(load clipsfiles/weaver/weaver12.clp)
(load clipsfiles/weaver/weaver13.clp)
(load clipsfiles/weaver/weaver14.clp)
(load clipsfiles/weaver/weaver15.clp)
(load clipsfiles/weaver/weaver16.clp)
(load clipsfiles/weaver/weaver17.clp)
(load clipsfiles/weaver/weaver18.clp)
(load clipsfiles/weaver/weaver19.clp)
(load clipsfiles/weaver/weaver20.clp)
(reset)
(run)
