/* Generated By:JJTree: Do not edit this line. SLAll.java */

package org.jamocha.parser.sl_old;

public class SLAll extends SimpleNode {
  public SLAll(int id) {
    super(id);
  }

  public SLAll(SLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
