/* Generated By:JJTree: Do not edit this line. SLB.java */

package org.jamocha.parser.sl_old;

public class SLB extends SimpleNode {
  public SLB(int id) {
    super(id);
  }

  public SLB(SLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
