/* Generated By:JJTree: Do not edit this line. SLEqual.java */

package org.jamocha.parser.sl_old;

public class SLEqual extends SimpleNode {
  public SLEqual(int id) {
    super(id);
  }

  public SLEqual(SLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
