/* Generated By:JJTree: Do not edit this line. SLFunctionalTerm.java */

package org.jamocha.parser.sl_old;

public class SLFunctionalTerm extends SimpleNode {
  public SLFunctionalTerm(int id) {
    super(id);
  }

  public SLFunctionalTerm(SLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
