/* Generated By:JJTree: Do not edit this line. SLI.java */

package org.jamocha.parser.sl_old;

public class SLI extends SimpleNode {
  public SLI(int id) {
    super(id);
  }

  public SLI(SLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
