/* Generated By:JJTree: Do not edit this line. SLNumericalConstant.java */

package org.jamocha.parser.sl_old;

public class SLNumericalConstant extends SimpleNode {
  public SLNumericalConstant(int id) {
    super(id);
  }

  public SLNumericalConstant(SLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
