/* Generated By:JJTree: Do not edit this line. SLSequence.java */

package org.jamocha.parser.sl_old;

public class SLSequence extends SimpleNode {
  public SLSequence(int id) {
    super(id);
  }

  public SLSequence(SLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
