/* Generated By:JJTree: Do not edit this line. SLTermOrIE.java */

package org.jamocha.parser.sl_old;

public class SLTermOrIE extends SimpleNode {
  public SLTermOrIE(int id) {
    super(id);
  }

  public SLTermOrIE(SLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
