/* Generated By:JJTree: Do not edit this line. SFPAndFunction.java */

package org.jamocha.parser.sfp;

public class SFPAndFunction extends SimpleNode {
  public SFPAndFunction(int id) {
    super(id);
  }

  public SFPAndFunction(SFPParser p, int id) {
    super(p, id);
  }

}
