/* Generated By:JJTree: Do not edit this line. SFPActionList.java */

package org.jamocha.parser.sfp;

public class SFPActionList extends SimpleNode {
  public SFPActionList(int id) {
    super(id);
  }

  public SFPActionList(SFPParser p, int id) {
    super(p, id);
  }

}
