/* Generated By:JJTree: Do not edit this line. SFPBooleanSymbol.java */

package org.jamocha.parser.sfp;

public class SFPBooleanSymbol extends SimpleNode {
  public SFPBooleanSymbol(int id) {
    super(id);
  }

  public SFPBooleanSymbol(SFPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SFPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
