/* Generated By:JJTree: Do not edit this line. SFPBoolean.java */

package org.jamocha.parser.sfp;

public class SFPBoolean extends SimpleNode {
  public SFPBoolean(int id) {
    super(id);
  }

  public SFPBoolean(SFPParser p, int id) {
    super(p, id);
  }

}
