/* Generated By:JJTree: Do not edit this line. SFPBooleanFunction.java */

package org.jamocha.parser.sfp;

public class SFPBooleanFunction extends SimpleNode {
  public SFPBooleanFunction(int id) {
    super(id);
  }

  public SFPBooleanFunction(SFPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SFPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
