/* Generated By:JJTree: Do not edit this line. SFPConnectedConstraint.java */

package org.jamocha.parser.sfp;

public class SFPConnectedConstraint extends SimpleNode {
  public SFPConnectedConstraint(int id) {
    super(id);
  }

  public SFPConnectedConstraint(SFPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SFPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
