/* Generated By:JJTree: Do not edit this line. SFPColon.java */

package org.jamocha.parser.sfp;

public class SFPColon extends SimpleNode {
  public SFPColon(int id) {
    super(id);
  }

  public SFPColon(SFPParser p, int id) {
    super(p, id);
  }

}
