/* Generated By:JJTree: Do not edit this line. SFPCaseStatement.java */

package org.jamocha.parser.sfp;

public class SFPCaseStatement extends SimpleNode {
  public SFPCaseStatement(int id) {
    super(id);
  }

  public SFPCaseStatement(SFPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SFPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
