/* Generated By:JJTree: Do not edit this line. SFPConstructDescription.java */

package org.jamocha.parser.sfp;

public class SFPConstructDescription extends SimpleNode {
  public SFPConstructDescription(int id) {
    super(id);
  }

  public SFPConstructDescription(SFPParser p, int id) {
    super(p, id);
  }

}
