/* Generated By:JJTree: Do not edit this line. SFPDeffunctionConstruct.java */

package org.jamocha.parser.sfp;

public class SFPDeffunctionConstruct extends SimpleNode {
  public SFPDeffunctionConstruct(int id) {
    super(id);
  }

  public SFPDeffunctionConstruct(SFPParser p, int id) {
    super(p, id);
  }

}
