/* Generated By:JJTree: Do not edit this line. SFPDeclaration.java */

package org.jamocha.parser.sfp;

public class SFPDeclaration extends SimpleNode {
  public SFPDeclaration(int id) {
    super(id);
  }

  public SFPDeclaration(SFPParser p, int id) {
    super(p, id);
  }

}
