/* Generated By:JJTree: Do not edit this line. SFPDynamicAttribute.java */

package org.jamocha.parser.sfp;

public class SFPDynamicAttribute extends SimpleNode {
  public SFPDynamicAttribute(int id) {
    super(id);
  }

  public SFPDynamicAttribute(SFPParser p, int id) {
    super(p, id);
  }

}
