/* Generated By:JJTree: Do not edit this line. SFPExpression.java */

package org.jamocha.parser.sfp;

public class SFPExpression extends SimpleNode {
  public SFPExpression(int id) {
    super(id);
  }

  public SFPExpression(SFPParser p, int id) {
    super(p, id);
  }

}
