/* Generated By:JJTree: Do not edit this line. SFPExistsCE.java */

package org.jamocha.parser.sfp;

public class SFPExistsCE extends SimpleNode {
  public SFPExistsCE(int id) {
    super(id);
  }

  public SFPExistsCE(SFPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SFPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
