/* Generated By:JJTree: Do not edit this line. SFPFindFactByFactFunc.java */

package org.jamocha.parser.sfp;

public class SFPFindFactByFactFunc extends SimpleNode {
  public SFPFindFactByFactFunc(int id) {
    super(id);
  }

  public SFPFindFactByFactFunc(SFPParser p, int id) {
    super(p, id);
  }

}
