/* Generated By:JJTree: Do not edit this line. SFPFloatList.java */

package org.jamocha.parser.sfp;

public class SFPFloatList extends SimpleNode {
  public SFPFloatList(int id) {
    super(id);
  }

  public SFPFloatList(SFPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SFPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
