/* Generated By:JJTree: Do not edit this line. SFPFunctionGroup.java */

package org.jamocha.parser.sfp;

public class SFPFunctionGroup extends SimpleNode {
  public SFPFunctionGroup(int id) {
    super(id);
  }

  public SFPFunctionGroup(SFPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SFPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
