/* Generated By:JJTree: Do not edit this line. SFPLexemeList.java */

package org.jamocha.parser.sfp;

public class SFPLexemeList extends SimpleNode {
  public SFPLexemeList(int id) {
    super(id);
  }

  public SFPLexemeList(SFPParser p, int id) {
    super(p, id);
  }

}
