/* Generated By:JJTree: Do not edit this line. SFPLHSSlot.java */

package org.jamocha.parser.sfp;

public class SFPLHSSlot extends SimpleNode {
  public SFPLHSSlot(int id) {
    super(id);
  }

  public SFPLHSSlot(SFPParser p, int id) {
    super(p, id);
  }

}
