/* Generated By:JJTree: Do not edit this line. SFPLogicalCE.java */

package org.jamocha.parser.sfp;

public class SFPLogicalCE extends SimpleNode {
  public SFPLogicalCE(int id) {
    super(id);
  }

  public SFPLogicalCE(SFPParser p, int id) {
    super(p, id);
  }

}
