/* Generated By:JJTree: Do not edit this line. SFPMultiSlotDefinition.java */

package org.jamocha.parser.sfp;

public class SFPMultiSlotDefinition extends SimpleNode {
  public SFPMultiSlotDefinition(int id) {
    super(id);
  }

  public SFPMultiSlotDefinition(SFPParser p, int id) {
    super(p, id);
  }

}
