/* Generated By:JJTree: Do not edit this line. SFPNumberList.java */

package org.jamocha.parser.sfp;

public class SFPNumberList extends SimpleNode {
  public SFPNumberList(int id) {
    super(id);
  }

  public SFPNumberList(SFPParser p, int id) {
    super(p, id);
  }

}
