/* Generated By:JJTree: Do not edit this line. SFPNoneAttribute.java */

package org.jamocha.parser.sfp;

public class SFPNoneAttribute extends SimpleNode {
  public SFPNoneAttribute(int id) {
    super(id);
  }

  public SFPNoneAttribute(SFPParser p, int id) {
    super(p, id);
  }

}
