/* Generated By:JJTree: Do not edit this line. SFPOrderedLHSFactBody.java */

package org.jamocha.parser.sfp;

public class SFPOrderedLHSFactBody extends SimpleNode {
  public SFPOrderedLHSFactBody(int id) {
    super(id);
  }

  public SFPOrderedLHSFactBody(SFPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SFPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
