/* Generated By:JJTree: Do not edit this line. SFPOrFunction.java */

package org.jamocha.parser.sfp;

public class SFPOrFunction extends SimpleNode {
  public SFPOrFunction(int id) {
    super(id);
  }

  public SFPOrFunction(SFPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SFPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
