/* Generated By:JJTree: Do not edit this line. /Users/charlie/Documents/workspace/jamocha/src/main/org/jamocha/parser/sfp/SFPParserTreeConstants.java */

package org.jamocha.parser.sfp;

public interface SFPParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTFLOAT = 1;
  public int JJTINTEGER = 2;
  public int JJTDATETIME = 3;
  public int JJTVOID = 4;
  public int JJTSYMBOL = 5;
  public int JJTSTRING = 6;
  public int JJTTRUE = 7;
  public int JJTSYMBOLTYPE = 8;
  public int JJTSTRINGTYPE = 9;
  public int JJTDATETIMETYPE = 10;
  public int JJTLEXEMETYPE = 11;
  public int JJTBOOLEANTYPE = 12;
  public int JJTINTEGERTYPE = 13;
  public int JJTLONGTYPE = 14;
  public int JJTSHORTTYPE = 15;
  public int JJTFLOATTYPE = 16;
  public int JJTDOUBLETYPE = 17;
  public int JJTNUMBERTYPE = 18;
  public int JJTFALSE = 19;
  public int JJTCONSTRUCTDESCRIPTION = 20;
  public int JJTSINGLEVARIABLE = 21;
  public int JJTGLOBALVARIABLE = 22;
  public int JJTMULTIVARIABLE = 23;
  public int JJTVARIABLE = 24;
  public int JJTVARIABLETYPE = 25;
  public int JJTFUNCTIONCALL = 26;
  public int JJTANYFUNCTION = 27;
  public int JJTEXPRESSION = 28;
  public int JJTASSERTFUNC = 29;
  public int JJTFINDFACTBYFACTFUNC = 30;
  public int JJTRETRACTFUNC = 31;
  public int JJTIFELSEFUNC = 32;
  public int JJTWHILEFUNC = 33;
  public int JJTLOOPFORCNTFUNC = 34;
  public int JJTSWITCHCASEFUNC = 35;
  public int JJTCASESTATEMENT = 36;
  public int JJTSWITCHDEFAULTS = 37;
  public int JJTDEFTEMPLATECONSTRUCT = 38;
  public int JJTSINGLESLOTDEFINITION = 39;
  public int JJTMULTISLOTDEFINITION = 40;
  public int JJTTEMPLATEATTRIBUTE = 41;
  public int JJTATTRIBUTES = 42;
  public int JJTDEFAULTATTRIBUTE = 43;
  public int JJTDEFAULTATTRIBUTES = 44;
  public int JJTDERIVEATTRIBUTE = 45;
  public int JJTNONEATTRIBUTE = 46;
  public int JJTDYNAMICATTRIBUTE = 47;
  public int JJTTEMPLATERHSPATTERN = 48;
  public int JJTRHSSLOT = 49;
  public int JJTDEFRULECONSTRUCT = 50;
  public int JJTACTIONLIST = 51;
  public int JJTDECLARATION = 52;
  public int JJTSALIENCE = 53;
  public int JJTAUTOFOCUS = 54;
  public int JJTRULEVERSION = 55;
  public int JJTCONDITIONALELEMENT = 56;
  public int JJTNOTFUNCTION = 57;
  public int JJTANDFUNCTION = 58;
  public int JJTORFUNCTION = 59;
  public int JJTASSIGNEDPATTERNCE = 60;
  public int JJTLOGICALCE = 61;
  public int JJTTESTCE = 62;
  public int JJTEXISTSCE = 63;
  public int JJTFORALLCE = 64;
  public int JJTTEMPLATEPATTERNCE = 65;
  public int JJTATTRIBUTECONSTRAINT = 66;
  public int JJTLHSSLOT = 67;
  public int JJTSINGLEFIELDWILDCARD = 68;
  public int JJTMULTIFIELDWILDCARD = 69;
  public int JJTCONNECTEDCONSTRAINT = 70;
  public int JJTAMPERSAND = 71;
  public int JJTLINE = 72;
  public int JJTTERM = 73;
  public int JJTNEGATION = 74;
  public int JJTCOLON = 75;
  public int JJTEQUALS = 76;
  public int JJTDEFGLOBALCONSTRUCT = 77;
  public int JJTGLOBALASSIGNMENT = 78;
  public int JJTDEFFUNCTIONCONSTRUCT = 79;
  public int JJTDEFGENERICCONSTRUCT = 80;
  public int JJTPARAMETERRESTRICTION = 81;
  public int JJTWILDCARDPARAMETERRESTRICTION = 82;
  public int JJTQUERY = 83;
  public int JJTTYPEATTRIBUTE = 84;
  public int JJTTYPESPECIFICATION = 85;
  public int JJTALLOWEDCONSTANTATTRIBUTE = 86;
  public int JJTSYMBOLLIST = 87;
  public int JJTSTRINGLIST = 88;
  public int JJTLEXEMELIST = 89;
  public int JJTINTEGERLIST = 90;
  public int JJTFLOATLIST = 91;
  public int JJTNUMBERLIST = 92;
  public int JJTVALUELIST = 93;
  public int JJTRANGEATTRIBUTE = 94;
  public int JJTRANGESPECIFICATION = 95;
  public int JJTCARDINALITYATTRIBUTE = 96;
  public int JJTCARDINALITYSPECIFICATION = 97;
  public int JJTDEFMODULECONSTRUCT = 98;


  public String[] jjtNodeName = {
    "Start",
    "Float",
    "Integer",
    "DateTime",
    "void",
    "Symbol",
    "String",
    "True",
    "SymbolType",
    "StringType",
    "DateTimeType",
    "LexemeType",
    "BooleanType",
    "IntegerType",
    "LongType",
    "ShortType",
    "FloatType",
    "DoubleType",
    "NumberType",
    "False",
    "ConstructDescription",
    "SingleVariable",
    "GlobalVariable",
    "MultiVariable",
    "Variable",
    "VariableType",
    "FunctionCall",
    "AnyFunction",
    "Expression",
    "AssertFunc",
    "FindFactByFactFunc",
    "RetractFunc",
    "IfElseFunc",
    "WhileFunc",
    "LoopForCntFunc",
    "SwitchCaseFunc",
    "CaseStatement",
    "SwitchDefaults",
    "DeftemplateConstruct",
    "SingleSlotDefinition",
    "MultiSlotDefinition",
    "TemplateAttribute",
    "Attributes",
    "DefaultAttribute",
    "DefaultAttributes",
    "DeriveAttribute",
    "NoneAttribute",
    "DynamicAttribute",
    "TemplateRHSPattern",
    "RHSSlot",
    "DefruleConstruct",
    "ActionList",
    "Declaration",
    "Salience",
    "AutoFocus",
    "RuleVersion",
    "ConditionalElement",
    "NotFunction",
    "AndFunction",
    "OrFunction",
    "AssignedPatternCE",
    "LogicalCE",
    "TestCE",
    "ExistsCE",
    "ForallCE",
    "TemplatePatternCE",
    "AttributeConstraint",
    "LHSSlot",
    "SingleFieldWildcard",
    "MultiFieldWildcard",
    "ConnectedConstraint",
    "Ampersand",
    "Line",
    "Term",
    "Negation",
    "Colon",
    "Equals",
    "DefglobalConstruct",
    "GlobalAssignment",
    "DeffunctionConstruct",
    "DefgenericConstruct",
    "ParameterRestriction",
    "WildcardParameterRestriction",
    "Query",
    "TypeAttribute",
    "TypeSpecification",
    "AllowedConstantAttribute",
    "SymbolList",
    "StringList",
    "LexemeList",
    "IntegerList",
    "FloatList",
    "NumberList",
    "ValueList",
    "RangeAttribute",
    "RangeSpecification",
    "CardinalityAttribute",
    "CardinalitySpecification",
    "DefmoduleConstruct",
  };
}
