/* Generated By:JJTree: Do not edit this line. SFPQuery.java */

package org.jamocha.parser.sfp;

public class SFPQuery extends SimpleNode {
  public SFPQuery(int id) {
    super(id);
  }

  public SFPQuery(SFPParser p, int id) {
    super(p, id);
  }

}
