/* Generated By:JJTree: Do not edit this line. SFPRuleProperty.java */

package org.jamocha.parser.sfp;

public class SFPRuleProperty extends SimpleNode {
  public SFPRuleProperty(int id) {
    super(id);
  }

  public SFPRuleProperty(SFPParser p, int id) {
    super(p, id);
  }

}
