/* Generated By:JJTree: Do not edit this line. SFPRangeSpecification.java */

package org.jamocha.parser.sfp;

public class SFPRangeSpecification extends SimpleNode {
  public SFPRangeSpecification(int id) {
    super(id);
  }

  public SFPRangeSpecification(SFPParser p, int id) {
    super(p, id);
  }

}
