/* Generated By:JJTree: Do not edit this line. SFPSwitchCaseFunc.java */

package org.jamocha.parser.sfp;

public class SFPSwitchCaseFunc extends SimpleNode {
  public SFPSwitchCaseFunc(int id) {
    super(id);
  }

  public SFPSwitchCaseFunc(SFPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SFPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
