/* Generated By:JJTree: Do not edit this line. SFPSymbolType.java */

package org.jamocha.parser.sfp;

public class SFPSymbolType extends SimpleNode {
  public SFPSymbolType(int id) {
    super(id);
  }

  public SFPSymbolType(SFPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SFPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
