/* Generated By:JJTree: Do not edit this line. SFPSymbol.java */

package org.jamocha.parser.sfp;

public class SFPSymbol extends SimpleNode {
  public SFPSymbol(int id) {
    super(id);
  }

  public SFPSymbol(SFPParser p, int id) {
    super(p, id);
  }

}
