/* Generated By:JJTree: Do not edit this line. SFPSwitchDefaults.java */

package org.jamocha.parser.sfp;

public class SFPSwitchDefaults extends SimpleNode {
  public SFPSwitchDefaults(int id) {
    super(id);
  }

  public SFPSwitchDefaults(SFPParser p, int id) {
    super(p, id);
  }

}
