/* Generated By:JJTree: Do not edit this line. SFPStringList.java */

package org.jamocha.parser.sfp;

public class SFPStringList extends SimpleNode {
  public SFPStringList(int id) {
    super(id);
  }

  public SFPStringList(SFPParser p, int id) {
    super(p, id);
  }

}
