/* Generated By:JJTree: Do not edit this line. SFPTemplateRHSPattern.java */

package org.jamocha.parser.sfp;

public class SFPTemplateRHSPattern extends SimpleNode {
  public SFPTemplateRHSPattern(int id) {
    super(id);
  }

  public SFPTemplateRHSPattern(SFPParser p, int id) {
    super(p, id);
  }

}
