/* Generated By:JJTree: Do not edit this line. SFPTrue.java */

package org.jamocha.parser.sfp;

public class SFPTrue extends SimpleNode {
  public SFPTrue(int id) {
    super(id);
  }

  public SFPTrue(SFPParser p, int id) {
    super(p, id);
  }

}
