/* Generated By:JJTree: Do not edit this line. SFPTemplatePatternCE.java */

package org.jamocha.parser.sfp;

public class SFPTemplatePatternCE extends SimpleNode {
  public SFPTemplatePatternCE(int id) {
    super(id);
  }

  public SFPTemplatePatternCE(SFPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SFPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
