/* Generated By:JJTree: Do not edit this line. SFPType.java */

package org.jamocha.parser.sfp;

public class SFPType extends SimpleNode {
  public SFPType(int id) {
    super(id);
  }

  public SFPType(SFPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SFPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
