/* Generated By:JJTree: Do not edit this line. SFPUnorderedLHSFactBody.java */

package org.jamocha.parser.sfp;

public class SFPUnorderedLHSFactBody extends SimpleNode {
  public SFPUnorderedLHSFactBody(int id) {
    super(id);
  }

  public SFPUnorderedLHSFactBody(SFPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SFPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
