/* Generated By:JJTree: Do not edit this line. SFPVariableType.java */

package org.jamocha.parser.sfp;

public class SFPVariableType extends SimpleNode {
  public SFPVariableType(int id) {
    super(id);
  }

  public SFPVariableType(SFPParser p, int id) {
    super(p, id);
  }

}
