/* Generated By:JJTree: Do not edit this line. SFPValueList.java */

package org.jamocha.parser.sfp;

public class SFPValueList extends SimpleNode {
  public SFPValueList(int id) {
    super(id);
  }

  public SFPValueList(SFPParser p, int id) {
    super(p, id);
  }

}
