/* Generated By:JJTree: Do not edit this line. SFPWildcardParameterRestriction.java */

package org.jamocha.parser.sfp;

public class SFPWildcardParameterRestriction extends SimpleNode {
  public SFPWildcardParameterRestriction(int id) {
    super(id);
  }

  public SFPWildcardParameterRestriction(SFPParser p, int id) {
    super(p, id);
  }

}
