/* Generated By:JJTree: Do not edit this line. SFPWhileFunc.java */

package org.jamocha.parser.sfp;

public class SFPWhileFunc extends SimpleNode {
  public SFPWhileFunc(int id) {
    super(id);
  }

  public SFPWhileFunc(SFPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SFPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
