/* Generated By:JJTree: Do not edit this line. COOLCEList.java */
package org.jamocha.parser.cool;

/** Node implementation for Construct nodes, basically adds Docstrings to
	SimpleNode class. All constructs in COOLParser may have docstrings, so 
	collecting the feature in a base class makes sense.
*/
public class ConstructNode extends SimpleNode {
	String doc;	// Optional Docstring

	public ConstructNode(int id) {
		super(id);
		doc="";
	}
	
	public ConstructNode(COOLParser p, int id) {
		super(p, id);
		doc="";
	}

	public void setDocString(String ds)
	{ doc=ds; }

	public String getDocString(String ds)
	{ return doc; }
}
