/* Generated By:JJTree: Do not edit this line. COOLGlobalAssignment.java */
package org.jamocha.parser.cool;

import org.jamocha.rete.Parameter;

public class COOLGlobalAssignment extends SimpleNode {
    public COOLGlobalAssignment(int id) {
	super(id);
    }

    public COOLGlobalAssignment(COOLParser p, int id) {
	super(p, id);
    }

    public String toString() {
	return "Global Assignment: " + name + " =";
    }

    public Parameter getExpression() {
	// // Global assignments have exactly one subtree with one expression
	// if (jjtGetNumChildren()==0) return JamochaValue.FALSE;
	// else engine.declareDefglobal(name,jjtGetChild(0).getExpression());
	// return JamochaValue.TRUE;
	return null;
    }

}
