/* Generated By:JJTree: Do not edit this line. CLIPS_SLString.java */
/** AST Node representing a String.
	@author jjTree
	@author Ory Chowaw-Liebman
*/
package org.jamocha.parser.cool;

import org.jamocha.parser.*;
import org.jamocha.rete.Rete;

public class COOLString extends SimpleNode {

	public COOLString(int id) {
		super(id);
	}

	public COOLString(COOLParser p, int id) {
		super(p, id);
	}
	
	public String toString() {
		return "String: " + name;
	}

	public boolean compareTree(SimpleNode n)
	{
		int i;
		// Do both nodes have the same id?
		if (id!=n.getId()) return false;
		// Do both nodes have the same contents?
		if (name!=n.getName()) return false;
		// Yes, they do
		return true;
	}

	public JamochaValue getValue(Rete engine) throws EvaluationException
	{
		return new JamochaValue(JamochaType.STRING,name);
	}
}
