/* Generated By:JJTree: Do not edit this line. CLIPS_SLGlobalVariable.java */
/** AST Node representing a Global variable.
 @author jjTree
 @author Ory Chowaw-Liebman
 */
package org.jamocha.parser.cool;

import org.jamocha.rete.BoundParam;
import org.jamocha.rete.Parameter;

public class COOLGlobalVariable extends SimpleNode {

    public COOLGlobalVariable(int id) {
	super(id);
    }

    public COOLGlobalVariable(COOLParser p, int id) {
	super(p, id);
    }

    public String toString() {
	return "Global Variable: " + name;
    }

    public Parameter getExpression() {
	BoundParam boundParam = new BoundParam();
	boundParam.setVariableName(name);
	return boundParam;
    }
}
