/* Generated By:JJTree: Do not edit this line. COOLFindFactByFactFunc.java */

package org.jamocha.parser.cool;

import org.jamocha.parser.EvaluationException;
import org.jamocha.parser.IllegalTypeException;
import org.jamocha.parser.JamochaType;
import org.jamocha.parser.JamochaValue;
import org.jamocha.rete.Fact;
import org.jamocha.rete.Rete;

public class COOLFindFactByFactFunc extends SimpleNode {
    public COOLFindFactByFactFunc(int id) {
	super(id);
    }

    public COOLFindFactByFactFunc(COOLParser p, int id) {
	super(p, id);
    }

    @Override
    public JamochaValue getValue(Rete engine) throws EvaluationException {
	JamochaValue factValue=jjtGetChild(0).getValue(engine);
	if (factValue.is(JamochaType.FACT))  {
	    Fact templateFact =factValue.getFactValue();
	    Fact existingFact = engine.getFact(templateFact);
	    if(existingFact == null) {
		return JamochaValue.NIL;
	    } else {
		return JamochaValue.newFactId(existingFact.getFactId());
	    }
	}
	throw new IllegalTypeException(JamochaType.FACTS, factValue.getType());
    }
    
    

}
