/* Generated By:JJTree: Do not edit this line. COOLDefgenericConstruct.java */
package org.jamocha.parser.cool;

import org.jamocha.parser.*;

public class COOLDefgenericConstruct extends ConstructNode {
  public COOLDefgenericConstruct(int id) {
    super(id);
  }

  public COOLDefgenericConstruct(COOLParser p, int id) {
    super(p, id);
  }

	public String toString() {
		return "defgeneric \"" + name + "\"" + "(" + doc + ")";
	}
	public JamochaValue execute() //throws EvaluationException
	{
		return JamochaValue.TRUE;
	};
}
