/* Generated By:JJTree: Do not edit this line. COOLParameterRestriction.java */
package org.jamocha.parser.cool;

public class COOLParameterRestriction extends SimpleNode {
  public COOLParameterRestriction(int id) {
    super(id);
  }

  public COOLParameterRestriction(COOLParser p, int id) {
    super(p, id);
  }

}
