/* Generated By:JJTree: Do not edit this line. COOLAttributes.java */

package org.jamocha.parser.cool;

import org.jamocha.rete.ExpressionList;
import org.jamocha.rete.Parameter;

public class COOLAttributes extends SimpleNode {
    public COOLAttributes(int id) {
	super(id);
    }

    public COOLAttributes(COOLParser p, int id) {
	super(p, id);
    }

    public Parameter getExpression() {
	ExpressionList expressionList = new ExpressionList();
	for (int i = 0; i < jjtGetNumChildren(); ++i) {
	    expressionList.add(jjtGetChild(i).getExpression());
	}
	return expressionList;
    };

}
