/* Generated By:JJTree: Do not edit this line. COOLOrderedRHSPattern.java */
package org.jamocha.parser.cool;

import org.jamocha.rete.Deffact;
import org.jamocha.rete.Parameter;

public class COOLOrderedRHSPattern extends SimpleNode {

	Deffact fact;
	
	public COOLOrderedRHSPattern(int id) {
		super(id);
	}

	public COOLOrderedRHSPattern(COOLParser p, int id) {
		super(p, id);
	}

	public Parameter getExpression()
	{
		// Not implemented in Jamocha, use Template Facts for now!
		//return JamochaValue.FALSE;
	    return null;
	}

}
