/* Generated By:JJTree: Do not edit this line. COOLCaseStatement.java */
package org.jamocha.parser.cool;

public class COOLCaseStatement extends SimpleNode {
  public COOLCaseStatement(int id) {
    super(id);
  }

  public COOLCaseStatement(COOLParser p, int id) {
    super(p, id);
  }

}
