/* Generated By:JJTree: Do not edit this line. CLIPS_SLString.java */
/** AST Node representing a String.
 @author jjTree
 @author Ory Chowaw-Liebman
 */
package org.jamocha.parser.cool;

import org.jamocha.parser.JamochaValue;
import org.jamocha.rete.Parameter;

public class COOLString extends SimpleNode {

    public COOLString(int id) {
	super(id);
    }

    public COOLString(COOLParser p, int id) {
	super(p, id);
    }

    public String toString() {
	return "String: " + name;
    }

    public Parameter getExpression() {
	return JamochaValue.newString(name);
    }
}
