/* Generated By:JJTree: Do not edit this line. COOLBooleanSymbol.java */

package org.jamocha.parser.cool;

import org.jamocha.parser.JamochaValue;
import org.jamocha.rete.Parameter;

public class COOLBooleanSymbol extends SimpleNode {
    protected boolean value;

    public COOLBooleanSymbol(int id) {
	super(id);
	value = false;
    }

    public COOLBooleanSymbol(COOLParser p, int id) {
	super(p, id);
	value = false;
    }

    public void setToTrue() {
	value = true;
    }

    public void setToFalse() {
	value = false;
    }

    public Parameter getExpression() {
	return value ? JamochaValue.TRUE : JamochaValue.FALSE;
    }
}
