/* Generated By:JJTree: Do not edit this line. CLIPS_SLFloat.java */
/** AST Node representing a Float.
	@author jjTree
	@author Ory Chowaw-Liebman
*/
package org.jamocha.parser.cool;

import org.jamocha.parser.*;
import org.jamocha.rete.Rete;

public class COOLFloat extends SimpleNode 
{
	private double value;

	public COOLFloat(int id) {
		super(id);
	}

	public COOLFloat(COOLParser p, int id) {
		super(p, id);
	}

	public void setName(String n) 
	{ 
		name = n; 
		value = Double.parseDouble( n ) ;
	}
	public String getName() { return name; }
	
	public String toString() {
		return "Float: " + name;
	}

	public boolean compareTree(SimpleNode n)
	{
		int i;
		// Do both nodes have the same id?
		if (id!=n.getId()) return false;
		// Do both nodes have the same contents?
		if (value!=((COOLFloat)n).value) return false;
		// Yes, they do
		return true;
	}

	public JamochaValue getValue(Rete engine) throws EvaluationException {
		return new JamochaValue(JamochaType.DOUBLE, value);
	}
}
