/* Generated By:JJTree: Do not edit this line. CLIPS_SLInstance.java */
/** AST Node representing an Instance.
	@author jjTree
	@author Ory Chowaw-Liebman
*/
package org.jamocha.parser.cool;

import org.jamocha.parser.JamochaType;
import org.jamocha.parser.JamochaValue;

public class COOLInstance extends SimpleNode 
{

	public COOLInstance(int id) {
		super(id);
	}

	public COOLInstance(COOLParser p, int id) {
		super(p, id);
	}

	public String toString() {
		return "Instance Name: " + name;
	}

	public boolean compareTree(SimpleNode n)
	{
		int i;
		// Do both nodes have the same id?
		if (id!=n.getId()) return false;
		// Do both nodes have the same name?
		if (getName()!=n.getName()) return false;
		// Yes, they do
		return true;
	}

	public JamochaValue execute() {
		return parser.getGlobalVar(name);
	}
}
