/* Generated By:JJTree: Do not edit this line. COOLType.java */
package org.jamocha.parser.cool;

public class COOLType extends SimpleNode {
  public COOLType(int id) {
    super(id);
  }

  public COOLType(COOLParser p, int id) {
    super(p, id);
  }

}
