/* Generated By:JJTree: Do not edit this line. /home/jupp/Projects/Eclipse Workspace/jamochaindex/src/main/org/jamocha/parser/cool/COOLParserTreeConstants.java */

package org.jamocha.parser.cool;

public interface COOLParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTFLOAT = 1;
  public int JJTINTEGER = 2;
  public int JJTDATETIME = 3;
  public int JJTVOID = 4;
  public int JJTSYMBOL = 5;
  public int JJTSTRING = 6;
  public int JJTINSTANCE = 7;
  public int JJTSINGLEVARIABLE = 8;
  public int JJTGLOBALVARIABLE = 9;
  public int JJTMULTIVARIABLE = 10;
  public int JJTANYFUNCTION = 11;
  public int JJTASSERTFUNC = 12;
  public int JJTRETRACTFUNC = 13;
  public int JJTIFELSEFUNC = 14;
  public int JJTWHILEFUNC = 15;
  public int JJTLOOPFORCNTFUNC = 16;
  public int JJTSWITCHCASEFUNC = 17;
  public int JJTCASESTATEMENT = 18;
  public int JJTDEFFACTSCONSTRUCT = 19;
  public int JJTDEFTEMPLATECONSTRUCT = 20;
  public int JJTORDEREDRHSPATTERN = 21;
  public int JJTTEMPLATERHSPATTERN = 22;
  public int JJTRHSSLOT = 23;
  public int JJTDEFRULECONSTRUCT = 24;
  public int JJTACTIONLIST = 25;
  public int JJTBOOLEANSYMBOL = 26;
  public int JJTTESTCE = 27;
  public int JJTLHSSLOT = 28;
  public int JJTSINGLEFIELDWILDCARD = 29;
  public int JJTMULTIFIELDWILDCARD = 30;
  public int JJTCONNECTEDCONSTRAINT = 31;
  public int JJTTERM = 32;
  public int JJTDEFGLOBALCONSTRUCT = 33;
  public int JJTGLOBALASSIGNMENT = 34;
  public int JJTDEFFUNCTIONCONSTRUCT = 35;
  public int JJTDEFGENERICCONSTRUCT = 36;
  public int JJTDEFMETHODCONSTRUCT = 37;
  public int JJTPARAMETERRESTRICTION = 38;
  public int JJTWILDCARDPARAMETERRESTRICTION = 39;
  public int JJTTYPE = 40;
  public int JJTQUERY = 41;
  public int JJTDEFCLASSCONSTRUCT = 42;
  public int JJTDEFMESSAGEHANDLERCONSTRUCT = 43;
  public int JJTDEFINSTANCESCONSTRUCT = 44;
  public int JJTDEFMODULECONSTRUCT = 45;
  public int JJTPORTSPECIFICATION = 46;
  public int JJTPORTITEM = 47;
  public int JJTCONSTRUCTNAME = 48;


  public String[] jjtNodeName = {
    "Start",
    "Float",
    "Integer",
    "DateTime",
    "void",
    "Symbol",
    "String",
    "Instance",
    "SingleVariable",
    "GlobalVariable",
    "MultiVariable",
    "AnyFunction",
    "AssertFunc",
    "RetractFunc",
    "IfElseFunc",
    "WhileFunc",
    "LoopForCntFunc",
    "SwitchCaseFunc",
    "CaseStatement",
    "DeffactsConstruct",
    "DeftemplateConstruct",
    "OrderedRHSPattern",
    "TemplateRHSPattern",
    "RHSSlot",
    "DefruleConstruct",
    "ActionList",
    "BooleanSymbol",
    "TestCE",
    "LHSSlot",
    "SingleFieldWildcard",
    "MultiFieldWildcard",
    "ConnectedConstraint",
    "Term",
    "DefglobalConstruct",
    "GlobalAssignment",
    "DeffunctionConstruct",
    "DefgenericConstruct",
    "DefmethodConstruct",
    "ParameterRestriction",
    "WildcardParameterRestriction",
    "Type",
    "Query",
    "DefclassConstruct",
    "DefmessageHandlerConstruct",
    "DefinstancesConstruct",
    "DefmoduleConstruct",
    "PortSpecification",
    "PortItem",
    "ConstructName",
  };
}
