/* Generated By:JJTree: Do not edit this line. COOLActionList.java */
package org.jamocha.parser.cool;

import org.jamocha.rete.ExpressionSequence;
import org.jamocha.rete.Parameter;

public class COOLActionList extends SimpleNode {
    public COOLActionList(int id) {
	super(id);
    }

    public COOLActionList(COOLParser p, int id) {
	super(p, id);
    }

    public Parameter getExpression() {
	ExpressionSequence expressionList = new ExpressionSequence();
	for (int i = 0; i < jjtGetNumChildren(); ++i) {
	    expressionList.add(jjtGetChild(i).getExpression());
	}
	return expressionList;
    }
}
