/* Generated By:JJTree: Do not edit this line. COOLRetractFunc.java */
package org.jamocha.parser.cool;

import org.jamocha.parser.*;
import org.jamocha.rete.Rete;

public class COOLRetractFunc extends SimpleNode {
  public COOLRetractFunc(int id) {
    super(id);
  }

  public COOLRetractFunc(COOLParser p, int id) {
    super(p, id);
  }

	public JamochaValue getValue(Rete engine) throws EvaluationException
	{
		return JamochaValue.FALSE;		
	};

}
