/* Generated By:JJTree: Do not edit this line. COOLRHSSlot.java */
package org.jamocha.parser.cool;

import org.jamocha.rete.ExpressionList;
import org.jamocha.rete.Parameter;
import org.jamocha.rete.SlotParam;

public class COOLRHSSlot extends SimpleNode {
    public COOLRHSSlot(int id) {
	super(id);
    }

    public COOLRHSSlot(COOLParser p, int id) {
	super(p, id);
    }

    // Build slots and return.
    public Parameter getExpression() {
	if (jjtGetNumChildren() == 1) { // Single Field Slot
	    return new SlotParam(name, jjtGetChild(0).getExpression());
	} else { // Multifield slot
	    ExpressionList slotValues = new ExpressionList();
	    for (int i = 0; i < jjtGetNumChildren(); i++) {
		slotValues.add(jjtGetChild(i).getExpression());
	    }
	    return new SlotParam(name, slotValues);
	}
    }
}
