/* Generated By:JJTree: Do not edit this line. COOLRetractFunc.java */
package org.jamocha.parser.cool;

import org.jamocha.rete.functions.RetractFunction;

public class COOLRetractFunc extends COOLAnyFunction {
    public COOLRetractFunc(int id) {
	super(id);
	setName(RetractFunction.NAME);
    }

    public COOLRetractFunc(COOLParser p, int id) {
	super(p, id);
	setName(RetractFunction.NAME);
    }
}
