/* Generated By:JJTree: Do not edit this line. COOLFindFactByFactFunc.java */

package org.jamocha.parser.cool;

import org.jamocha.rete.functions.rete.FindFactByFact;

public class COOLFindFactByFactFunc extends COOLAnyFunction {
    public COOLFindFactByFactFunc(int id) {
	super(id);
	setName(FindFactByFact.NAME);
    }

    public COOLFindFactByFactFunc(COOLParser p, int id) {
	super(p, id);
	setName(FindFactByFact.NAME);
    }
}
