/* Generated By:JJTree: Do not edit this line. CLIPS_SLMultiVariable.java */
/** AST Node representing a Symbol.
	@author jjTree
	@author Ory Chowaw-Liebman
*/
package org.jamocha.parser.cool;

import org.jamocha.rete.Parameter;

public class COOLMultiVariable extends SimpleNode 
{
	DeffunctionParams value;

	public COOLMultiVariable(int id) {
		super(id);
	}

	public COOLMultiVariable(COOLParser p, int id) {
		super(p, id);
	}
	
	public String toString() {
		return "Multi Variable: " + name;
	}

	public Parameter getExpression() {
	    // TODO
		return null;
	}
}
