/* Generated By:JJTree: Do not edit this line. COOLQuery.java */
package org.jamocha.parser.cool;

public class COOLQuery extends SimpleNode {
  public COOLQuery(int id) {
    super(id);
  }

  public COOLQuery(COOLParser p, int id) {
    super(p, id);
  }

}
