/* Generated By:JJTree: Do not edit this line. COOLAssertFunc.java */
package org.jamocha.parser.cool;

import org.jamocha.rete.functions.AssertFunction;

public class COOLAssertFunc extends COOLAnyFunction {
	
    public COOLAssertFunc(int id) {
		super(id);
		setName(AssertFunction.NAME);
	}

	public COOLAssertFunc(COOLParser p, int id) {
		super(p, id);
		setName(AssertFunction.NAME);
	}
}
