/* Generated By:JJTree: Do not edit this line. CLIPS_SLSingleVariable.java */
/** AST Node representing a Symbol.
	@author jjTree
	@author Ory Chowaw-Liebman
*/
package org.jamocha.parser.cool;

import org.jamocha.parser.JamochaValue;
import org.jamocha.rete.Rete;

public class COOLSingleVariable extends SimpleNode 
{
	DeffunctionParams value=null;

	public COOLSingleVariable(int id) {
		super(id);
	}

	public COOLSingleVariable(COOLParser p, int id) {
		super(p, id);
	}	

	public String toString() {
		return "Single Variable: " + name;
	}


	public JamochaValue getValue(Rete engine) {
		return engine.getBinding(name);
	}
}
