/* Generated By:JJTree: Do not edit this line. CLIPS_SLInteger.java */
/** AST Node representing an Integer.
	@author jjTree
	@author Ory Chowaw-Liebman
*/
package org.jamocha.parser.cool;

import org.jamocha.parser.*;
import org.jamocha.rete.Rete;


public class COOLInteger extends SimpleNode 
{

	private long value;

	public void setName(String n) 
	{ 
		name = n; 
		value = Long.parseLong( n ) ;
	}
	public String getName() { return name; }

	public COOLInteger(int id) {
		super(id);
	}

	public COOLInteger(COOLParser p, int id) {
		super(p, id);
	}
	
	public String toString() {
		return "Integer: " + name;
	}
	
	public boolean compareTree(SimpleNode n)
	{
		int i;
		// Do both nodes have the same id?
		if (id!=n.getId()) return false;
		// Do both nodes have the same contents?
		if (value!=((COOLInteger)n).value) return false;
		// Yes, they do
		return true;
	}
	
	public JamochaValue getValue(Rete engine) throws EvaluationException {
		return new JamochaValue(JamochaType.LONG, value);
	}
}
