/* Generated By:JJTree: Do not edit this line. COOLDefFactsConstruct.java */

package org.jamocha.parser.cool;

import org.jamocha.rete.Parameter;

public class COOLDeffactsConstruct extends ConstructNode {
    public COOLDeffactsConstruct(int id) {
	super(id);
    }

    public COOLDeffactsConstruct(COOLParser p, int id) {
	super(p, id);
    }

    public String toString() {
	return "deffact \"" + name + "\"" + " (" + doc + ")";
    }

    public Parameter getExpression() {
	return null;
    }
}
