/* Generated By:JJTree: Do not edit this line. COOLWildcardParameterRestriction.java */
package org.jamocha.parser.cool;


public class COOLWildcardParameterRestriction extends SimpleNode {
  public COOLWildcardParameterRestriction(int id) {
    super(id);
  }

  public COOLWildcardParameterRestriction(COOLParser p, int id) {
    super(p, id);
  }

}
